In [1]:
from Connected_KB import Connected_KB

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
kb = Connected_KB()

In [4]:
len(kb.ConceptNet), len(kb.ATOMIC_Events), len(kb.ATOMIC_Infers)

(304666, 24312, 284445)

In [76]:
kb.ConceptNet['attacked']

{'atomic_event': [],
 'conceptnet': [{'rel': 'hassubevent', 'tail': 'fight_back', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'kill', 'direction': 1},
  {'rel': 'notdesires', 'tail': 'animal', 'direction': 1}],
 'atomic_infer': {'are attacked',
  "are attacked by persony's army",
  'attacked',
  'attacked by a bear',
  'attacked by a dog',
  'attacked by dog',
  'attacked by foxes',
  'attacked by media',
  'attacked by shark',
  'attacked by wild animal',
  'attacked.',
  'avoids being attacked',
  'emotionally attacked',
  'get attacked by a shark',
  'get chasted and get attacked.',
  'gets attacked',
  'gets attacked back',
  'gets attacked by a bear',
  'gets attacked by bear',
  'gets attacked by bigots',
  'gets attacked by mafia',
  'gets attacked by persony',
  'gets attacked by someone',
  'gets attacked by stray dogs',
  'gets attacked by y.',
  'gets attacked for lying',
  'gets attacked in the news',
  'is attacked',
  'is attacked back',
  'is attacked by a wild animal',
  'is attacked by birds',
  'is attacked by personx',
  'like they have been attacked',
  'may attacked by disease',
  'personx gets attacked.',
  'protects themselves from being attacked',
  'she gets attacked',
  'she gets attacked.',
  'they are attacked',
  'they get attacked',
  'thinks about getting attacked',
  'to be attacked by persony',
  'to have attacked',
  'troops are attacked',
  'verbally attacked'}}

In [ ]:
for kb_type, kb_

In [60]:
kb.ATOMIC_Infers['becomes educated']

{'conceptnet': {'become', 'educated'},
 'atomic_event': [{'rel': 'xEffect',
   'tail': "PersonX asks PersonY's neighbor"},
  {'rel': 'xEffect', 'tail': 'PersonX gets back to school'},
  {'rel': 'oEffect', 'tail': 'PersonX provides ___ to persons'},
  {'rel': 'oEffect', 'tail': 'PersonX sends ___ to college'},
  {'rel': 'xEffect', 'tail': 'PersonX studies for an exam'},
  {'rel': 'oEffect', 'tail': 'PersonX takes PersonY to school'},
  {'rel': 'oEffect', 'tail': 'PersonX teaches PersonY anything'},
  {'rel': 'xEffect', 'tail': 'PersonX wants to be healthy'},
  {'rel': 'oEffect', 'tail': "PersonX works PersonX's ___ through college"}]}

In [49]:
kb.ATOMIC_Events['PersonX adopts a new cat']

{'atomic_infer': {'oEffect': {'the cat dies', 'the cat runs away'},
  'oReact': set(),
  'oWant': {'meow', 'purr', 'to feed the cat', 'to welcome the cat'},
  'xAttr': {'affectionate',
   'caring',
   'compassionate',
   'happy',
   'lonely',
   'loving'},
  'xEffect': {'is covered in dander',
   'is required to buy food and litter box for cat',
   'personx smiles',
   'personx sneezes from the cat hair'},
  'xIntent': {'to have a pet'},
  'xNeed': {'go to adoption center',
   'have money for adoption fee',
   'to go to the pound',
   'to have cats',
   'to like cats',
   'to see what animals are there'},
  'xReact': {'happy', 'satisfied'},
  'xWant': {'purchase nail covers',
   'spay or neuter cat',
   'to bring the cat home',
   'to buy some cat food and litter',
   'to check if the cat is male or female',
   'to feed the cat',
   'to put the cat in their carrier'},
  'prefix': {'adopts', 'new'}},
 'conceptnet': {'adopt', 'new'}}

In [50]:
rel = kb.search_path_byEntity("kissing","uncomfortable",2)
print(len(rel))
for r in rel:
    for d in r:
        print(d['rel_w_parent'] if d['rel_w_parent'] else "->", "【", d["kb_type"].upper(), ":", d['key'], "】")
    print(" ")

2
-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sex 】
-> 【 ATOMIC_INFER : to resist having uncomfortable sex 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xNeed 【 ATOMIC_INFER : be uncomfortable 】

In [12]:
rel = kb.search_path_byEntity("kissing","smile",3)
print(len(rel))
for r in rel:
    for d in r:
        print(d['rel_w_parent'] if d['rel_w_parent'] else "->", "【", d["kb_type"].upper(), ":", d['key'], "】")
    print(" ")

874
-> 【 CONCEPTNET : kissing 】
capableof 【 CONCEPTNET : lovers 】
capableof 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
capableof 【 CONCEPTNET : lovers 】
capableof 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : going_see_film 】
usedfor 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : arousal 】
hassubevent 【 CONCEPTNET : enjoying_day 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : arousal 】
hassubevent 【 CONCEPTNET : enjoying_day 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
causes 【 CONCEPTNET : enjoying_day 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
causes 【 CONCEPTNET : enjoying_day 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
causes 【 CONCEPTNET : getting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
causes 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
causes 【 CONCEPTNET : meeting_friend 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
causes 【 CONCEPTNET : opening_gift 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
causes 【 CONCEPTNET : tasting_sweet 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
causes 【 CONCEPTNET : tasting_sweet 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
usedfor 【 CONCEPTNET : enjoying_day 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : being_happy 】
usedfor 【 CONCEPTNET : enjoying_day 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : catch_cold 】
hassubevent 【 CONCEPTNET : walk_in_rain 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : catch_cold 】
motivatedbygoal 【 CONCEPTNET : walk_in_rain 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : excitement 】
causes 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : excitement 】
causes 【 CONCEPTNET : hearing_crowd_go_mad 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : excitement 】
causes 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : excitement 】
causes 【 CONCEPTNET : meeting_friend 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : excitement 】
causes 【 CONCEPTNET : opening_gift 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : excitement 】
usedfor 【 CONCEPTNET : hearing_crowd_go_mad 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : excitement 】
-> 【 ATOMIC_EVENT : PersonX contains PersonX's excitement 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
causes 【 CONCEPTNET : attending_classical_concert 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
causes 【 CONCEPTNET : getting_good_grade 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
causes 【 CONCEPTNET : getting_physical_activity 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
causes 【 CONCEPTNET : tasting_sweet 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
causes 【 CONCEPTNET : tasting_sweet 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
hassubevent 【 CONCEPTNET : remembering 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
hassubevent 【 CONCEPTNET : remembering 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
usedfor 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
usedfor 【 CONCEPTNET : enjoying_day 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
usedfor 【 CONCEPTNET : enjoying_day 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
usedfor 【 CONCEPTNET : helping 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
usedfor 【 CONCEPTNET : howling_with_laughter 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : feeling_good 】
usedfor 【 CONCEPTNET : looking_better 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : attending_classical_concert 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : enjoying_day 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : enjoying_day 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : enjoying_film 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : getting_good_grade 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : going_to_performance 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : helping 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : howling_with_laughter 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : looking_better 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : making_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : meeting_friend 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : opening_gift 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : performing 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : reading_letter 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : serving_customers 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
causes 【 CONCEPTNET : winning_baseball_game 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
hassubevent 【 CONCEPTNET : buying_shirt 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
hassubevent 【 CONCEPTNET : enjoying_day 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
hassubevent 【 CONCEPTNET : enjoying_day 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
hassubevent 【 CONCEPTNET : receiving_degree 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
usedfor 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
usedfor 【 CONCEPTNET : reading_letter 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
usedfor 【 CONCEPTNET : remembering 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
usedfor 【 CONCEPTNET : remembering 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
-> 【 ATOMIC_INFER : to express happiness 】
xIntent 【 ATOMIC_EVENT : PersonX smiles broadly 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
-> 【 ATOMIC_INFER : happiness 】
xReact 【 ATOMIC_EVENT : PersonX smiles back at PersonY 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : happiness 】
-> 【 ATOMIC_INFER : to cause happiness 】
xIntent 【 ATOMIC_EVENT : PersonX makes PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
hasprerequisite 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
hasprerequisite 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
hasprerequisite 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : entertain 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : entertain 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : make_friends 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : make_friends 】
usedfor 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : taste_sweet 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
motivatedbygoal 【 CONCEPTNET : taste_sweet 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX cries like a PersonY 】
oEffect 【 ATOMIC_INFER : they smile to 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX cries like a PersonY 】
xEffect 【 ATOMIC_INFER : they smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX decides would like 】
oEffect 【 ATOMIC_INFER : they smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes PersonY a lot 】
oEffect 【 ATOMIC_INFER : is smiled at 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes PersonY a lot 】
xEffect 【 ATOMIC_INFER : smiles thinking about persony 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes PersonY anymore 】
xEffect 【 ATOMIC_INFER : personx smiles at persony. 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes PersonY back 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes PersonY's job 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes ___ though 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes ___ very much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes ___ well 】
xEffect 【 ATOMIC_INFER : smiles a lot 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes a boy 】
oEffect 【 ATOMIC_INFER : gets smiled at 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes animals 】
xEffect 【 ATOMIC_INFER : smiles when they see animals 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes it a lot 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes it a lot 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes it very much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes one 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes scary movies 】
xWant 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes that idea 】
xEffect 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes the game 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes the game 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes the idea 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes the idea 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes the job 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes the movie 】
xEffect 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes the movie 】
xEffect 【 ATOMIC_INFER : personx smiles at film. 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes the music 】
xEffect 【 ATOMIC_INFER : smiles while listening 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes to play 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX likes to play video games 】
xEffect 【 ATOMIC_INFER : personx smiles at the video game 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX looks ___ like PersonY 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX looks like a PersonY 】
xEffect 【 ATOMIC_INFER : they smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX looks like fun 】
xWant 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX looks like new 】
xWant 【 ATOMIC_INFER : smile at themselves 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX misses PersonY like crazy 】
oEffect 【 ATOMIC_INFER : persony gets the letter and smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX sees what it was like 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX shines like the sun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX smells like PersonY 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_EVENT : PersonX succeeds like success 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_INFER : to tell persony they like them 】
xWant 【 ATOMIC_EVENT : PersonX gives PersonY a smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_INFER : to like persony 】
xNeed 【 ATOMIC_EVENT : PersonX looks at PersonY with a smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : like 】
-> 【 ATOMIC_INFER : to like persony 】
xNeed 【 ATOMIC_EVENT : PersonX smiles upon PersonY 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : lipstick_on_cheek 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : lipstick_on_cheek 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
atlocation 【 CONCEPTNET : human 】
capableof 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causes 【 CONCEPTNET : meeting_people 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causes 【 CONCEPTNET : meeting_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : entertain 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : entertain 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : flirt 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : flirt 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : flirt 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : hear_singing 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : lie 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : make_friends 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : make_friends 】
usedfor 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : meet_friend 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】

distinctfrom 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : make_friends 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : make_friends 】
usedfor 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
mannerof 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
motivatedbygoal 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
motivatedbygoal 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
motivatedbygoal 【 CONCEPTNET : meet_girls 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
motivatedbygoal 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
usedfor 【 CONCEPTNET : killing_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
usedfor 【 CONCEPTNET : remembering 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
usedfor 【 CONCEPTNET : remembering 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX confesses PersonX's love 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX confesses PersonX's love 】
xEffect 【 ATOMIC_INFER : gets smiled at 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's ___ as PersonX's bodies 】
xEffect 【 ATOMIC_INFER : smiles with joy 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's beard 】
xEffect 【 ATOMIC_INFER : smiles in satisfaction 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's beard 】
xEffect 【 ATOMIC_INFER : personx smiles at themself in the mirror 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's beard 】
xWant 【 ATOMIC_INFER : smile at self 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's car 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's mother 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's new job 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's trip 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY back 】
xEffect 【 ATOMIC_INFER : they smile inadvertently 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY very much 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's car 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's dog 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's motorcycle 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's motorcycle 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's neighbor 】
xEffect 【 ATOMIC_INFER : personx smiles at persony's neighbor 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's new hair 】
oEffect 【 ATOMIC_INFER : they smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's new hair 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's new hair 】
xEffect 【 ATOMIC_INFER : he smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's new home 】
oEffect 【 ATOMIC_INFER : persony smiles and has sensations of pride. 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's work 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves ___ above all things 】
xEffect 【 ATOMIC_INFER : personx smiles at god's presence 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves ___ dearly 】
xEffect 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves ___ so much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves ___ very much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves coffee 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves every minute of it 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves gymnastics 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves helping people 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves helping people 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves it very much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves oranges 】
xEffect 【 ATOMIC_INFER : smiles thinking about oranges 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves playing video games 】
xEffect 【 ATOMIC_INFER : personx smiles at the videogame 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves riding PersonX's bike 】
xEffect 【 ATOMIC_INFER : smiles with joy 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves spending time 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the car 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the car 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the dog 】
xEffect 【 ATOMIC_INFER : smiles at the dog 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the dress 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the experience 】
xEffect 【 ATOMIC_INFER : has a wide smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the gift 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the meal 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the pictures 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the pictures 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the rain 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the show 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the song 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the view 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves to draw 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves to go fishing 】
xEffect 【 ATOMIC_INFER : smiles when going fishing 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves to go fishing 】
xEffect 【 ATOMIC_INFER : smiles when he catches a fish 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves very much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX shows PersonY's love 】
oEffect 【 ATOMIC_INFER : persony smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX shows PersonY's love 】
xEffect 【 ATOMIC_INFER : receives a smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX stills loves PersonY 】
oEffect 【 ATOMIC_INFER : smiles back 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX stills loves PersonY 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasurable 】
hasproperty 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasurable 】
motivatedbygoal 【 CONCEPTNET : copulate 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasurable 】
motivatedbygoal 【 CONCEPTNET : copulate 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : going_to_performance 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : opening_gift 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : remembering 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : remembering 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : tasting_sweet 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
causes 【 CONCEPTNET : tasting_sweet 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
hassubevent 【 CONCEPTNET : copulate 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
hassubevent 【 CONCEPTNET : copulate 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
hassubevent 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
hassubevent 【 CONCEPTNET : open_gift 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
motivatedbygoal 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
motivatedbygoal 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
motivatedbygoal 【 CONCEPTNET : make_friends 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
motivatedbygoal 【 CONCEPTNET : make_friends 】
usedfor 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
usedfor 【 CONCEPTNET : attending_classical_concert 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
usedfor 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
usedfor 【 CONCEPTNET : getting_physical_activity 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
usedfor 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
usedfor 【 CONCEPTNET : tasting_sweet 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
usedfor 【 CONCEPTNET : tasting_sweet 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
-> 【 ATOMIC_EVENT : PersonX affords PersonY pleasure 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
-> 【 ATOMIC_EVENT : PersonX gives PersonY the pleasure 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
-> 【 ATOMIC_EVENT : PersonX gives PersonY's pleasure 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : pleasure 】
-> 【 ATOMIC_EVENT : PersonX gives PersonY's pleasure 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sex 】
causes 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sex 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sex 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sex 】
motivatedbygoal 【 CONCEPTNET : flirt 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sex 】
motivatedbygoal 【 CONCEPTNET : flirt 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sex 】
motivatedbygoal 【 CONCEPTNET : flirt 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sexual_excitement 】
causes 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : smeared_lipstick 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : smeared_lipstick 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : strong_feelings 】
causesdesire 【 CONCEPTNET : hear_singing 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sleighing_ride 】
hassubevent 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sleighing_ride 】
hassubevent 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sleighing_ride 】
hassubevent 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
causes 【 CONCEPTNET : sleighing_ride 】
usedfor 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hasprerequisite 【 CONCEPTNET : flirt 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hasprerequisite 【 CONCEPTNET : flirt 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hasprerequisite 【 CONCEPTNET : flirt 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hasprerequisite 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : copulate 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : copulate 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : enjoying_film 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : surprising 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
motivatedbygoal 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX french kisses 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX gives PersonY a kiss 】
xEffect 【 ATOMIC_INFER : they smile at persony 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX gives ___ a kiss 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY back 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY back 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY hand 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY hand 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY hand 】

oWant 【 ATOMIC_INFER : to smile at personx 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY on both cheeks 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY on both cheeks 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY on the forehead 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY on the forehead 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY on the forehead 】
oWant 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY on the forehead 】
xEffect 【 ATOMIC_INFER : gets smiled at 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY on the forehead 】
xWant 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY on the lips 】
oEffect 【 ATOMIC_INFER : persony smiles at personx 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY softly 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's cheek 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's hand 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's hand 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's hand 】
oWant 【 ATOMIC_INFER : to give a smile to personx 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's hand 】
xWant 【 ATOMIC_INFER : get a smile from persony 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's hands 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's hands 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's hands 】
xEffect 【 ATOMIC_INFER : gets smiled at 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's lips 】
oWant 【 ATOMIC_INFER : smile at personx 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's lips 】
xWant 【 ATOMIC_INFER : smile at persony 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's ring 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's ring 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's shoulder 】
oEffect 【 ATOMIC_INFER : they smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses PersonY's shoulder 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses a girl 】
oWant 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses a girl 】
xEffect 【 ATOMIC_INFER : smiles at the girl 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses a girl 】
xWant 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_EVENT : PersonX kisses the top of PersonY's head 】
oWant 【 ATOMIC_INFER : to smile at personx 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_INFER : to kiss persony 】
xWant 【 ATOMIC_EVENT : PersonX smiles back at PersonY 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : kiss 】
-> 【 ATOMIC_INFER : personx kisses persony. 】
xEffect 【 ATOMIC_EVENT : PersonX makes PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : partner 】
motivatedbygoal 【 CONCEPTNET : look_better 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : partner 】
motivatedbygoal 【 CONCEPTNET : look_better 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : partner 】
motivatedbygoal 【 CONCEPTNET : meet_girls 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : trust 】
-> 【 ATOMIC_EVENT : PersonX puts PersonX's trust in PersonY 】
xEffect 【 ATOMIC_INFER : smiles when sees persony 】

-> 【 CONCEPTNET : kissing 】
hasprerequisite 【 CONCEPTNET : two_people 】
hasprerequisite 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : enjoyable 】
motivatedbygoal 【 CONCEPTNET : entertain 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : enjoyable 】
motivatedbygoal 【 CONCEPTNET : entertain 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : enjoyable 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : enjoyable 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : enjoyable 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : enjoying_film 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : getting_physical_activity 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : going_to_performance 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : pretending 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
causesdesire 【 CONCEPTNET : express_how_funny 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
causesdesire 【 CONCEPTNET : socialize 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
causesdesire 【 CONCEPTNET : socialize 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
hasprerequisite 【 CONCEPTNET : howling_with_laughter 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
hasproperty 【 CONCEPTNET : killing_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
hasproperty 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
hasproperty 【 CONCEPTNET : making_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
hassubevent 【 CONCEPTNET : chat_with_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
hassubevent 【 CONCEPTNET : flirt 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
hassubevent 【 CONCEPTNET : flirt 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
hassubevent 【 CONCEPTNET : flirt 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
isa 【 CONCEPTNET : listen_to_radio 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
isa 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : dreaming 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : enjoying_film 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : getting_physical_activity 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : going_to_performance 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : hiking 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : howling_with_laughter 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : surprising 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : talking_to 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : winning_baseball_game 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has a lot of fun playing 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has a ton of fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has fun playing 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has fun playing 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has fun with PersonX's friends 】
xEffect 【 ATOMIC_INFER : personx smiles from  fun. 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has fun with PersonY's friends 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has great fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has much fun 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has so much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has so much fun playing 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has too much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX is having a lot of fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX is so much fun 】
xWant 【 ATOMIC_INFER : make people smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX looks fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX makes fun of PersonY's 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX sounds fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : fun 】
-> 【 ATOMIC_INFER : to have fun 】
oWant 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
capableof 【 CONCEPTNET : helping 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
hasprerequisite 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
hasproperty 【 CONCEPTNET : human 】
capableof 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
nothasproperty 【 CONCEPTNET : killing_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX becomes good friends 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX becomes so good 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX delivers the goods 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX feels good 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX feels good 】
xEffect 【 ATOMIC_INFER : they smile. 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX feels good about PersonY's decision 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX feels good about herself 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX feels so good 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX feels so good 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX feels very good 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX feels very good 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX gets a good grade 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX gets a good grade 】
xEffect 【 ATOMIC_INFER : get a prize with smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX gets a good job 】
xEffect 【 ATOMIC_INFER : personx smiles at the new job 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX gets a good job 】
xEffect 【 ATOMIC_INFER : smiles more 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX gets a good spot 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX gets good 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX has a good laugh 】
xWant 【 ATOMIC_INFER : smile at someone 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX has a good life 】
xEffect 【 ATOMIC_INFER : smiles a lot 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX has a really good time 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX has such a good time 】
xEffect 【 ATOMIC_INFER : smiled 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX is a pretty good day 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX is as good as new 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX is in a good mood 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX looks good on PersonY 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX looks so good 】
oEffect 【 ATOMIC_INFER : they smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX looks so good 】
xEffect 【 ATOMIC_INFER : he smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX makes a good impression 】
oWant 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX makes a good impression 】
xNeed 【 ATOMIC_INFER : smile big. 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX says good morning 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX says good morning 】

xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX smells so good 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX sounds good to PersonY 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX sounds good to PersonY 】
xEffect 【 ATOMIC_INFER : smiles at persony 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX takes a good look 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX tells PersonY the good news 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_EVENT : PersonX thinks it was a good idea 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : good. 】
oReact 【 ATOMIC_EVENT : PersonX smiles back 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : good. 】
xReact 【 ATOMIC_EVENT : PersonX smiles back 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : to feel good 】
xWant 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : say good bye 】
xWant 【 ATOMIC_EVENT : PersonX smiles happily 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : good 】
xReact 【 ATOMIC_EVENT : PersonX looks at PersonY with a smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : good 】
xReact 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : good 】
xAttr 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : can easily have good relation with others 】
xEffect 【 ATOMIC_EVENT : PersonX gives PersonY a smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : good about them self 】
xReact 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : feel good about something 】
xNeed 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : to make personx feel good 】
oWant 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : good to brightening person's day 】
xReact 【 ATOMIC_EVENT : PersonX gives PersonY a smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : to be in a good mood 】
xNeed 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : to be in a good mood 】
xWant 【 ATOMIC_EVENT : PersonX smiles happily 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : good and probably happy 】
oReact 【 ATOMIC_EVENT : PersonX gives PersonY a smile 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : to tell persony good things 】
xWant 【 ATOMIC_EVENT : PersonX smiles upon PersonY 】

-> 【 CONCEPTNET : kissing 】
hasproperty 【 CONCEPTNET : good 】
-> 【 ATOMIC_INFER : to make personx have a good day 】
oWant 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
causes 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
causes 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
causes 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
causes 【 CONCEPTNET : winning_baseball_game 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
hassubevent 【 CONCEPTNET : happy 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
hassubevent 【 CONCEPTNET : happy 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
hassubevent 【 CONCEPTNET : happy 】
motivatedbygoal 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
hassubevent 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
hassubevent 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
hassubevent 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
hassubevent 【 CONCEPTNET : having_good_time 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
usedfor 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
usedfor 【 CONCEPTNET : having_good_time 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : celebrating 】
-> 【 ATOMIC_EVENT : PersonX is celebrating PersonY's birthday 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
causes 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX agrees to a date 】
xAttr 【 ATOMIC_INFER : all smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX asks PersonY on a date 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX asks PersonY out on a date 】
oEffect 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX asks ___ on a date 】
xNeed 【 ATOMIC_INFER : to smile at the girl in the coffee shop 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX asks ___ out on a date 】
oWant 【 ATOMIC_INFER : to smile because they didn't expect to be asked on a date 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX dates back to the time 】
xEffect 【 ATOMIC_INFER : they smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX gets a date with PersonY 】
oEffect 【 ATOMIC_INFER : persony smiles in excitement 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX gets a date with PersonY 】
xEffect 【 ATOMIC_INFER : personx smiles in excitement 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX goes on a date with PersonY 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX goes on a date with PersonY 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX impresses PersonY's date 】
oEffect 【 ATOMIC_INFER : persony's date smiles at personx 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX is going on a date 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX makes a date 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX makes a date 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX sets ___ up on a date 】
oEffect 【 ATOMIC_INFER : persony smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX takes PersonY on a date 】
oEffect 【 ATOMIC_INFER : smiles at personx 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_EVENT : PersonX takes PersonY on a date 】
xEffect 【 ATOMIC_INFER : smiles at persony 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_INFER : to ask persony for a date. 】
xWant 【 ATOMIC_EVENT : PersonX greets PersonY with a smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_INFER : to date personx, 】
oWant 【 ATOMIC_EVENT : PersonX greets PersonY with a smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : date 】
-> 【 ATOMIC_INFER : gets asked out on a date 】
oEffect 【 ATOMIC_EVENT : PersonX looks at PersonY with a smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : dating 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : dating 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : dating 】
usedfor 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : dating 】
usedfor 【 CONCEPTNET : improving_image 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : dating 】
-> 【 ATOMIC_EVENT : PersonX is dating a girl 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : meet_girls 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : flirting 】
usedfor 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : flirting 】
usedfor 【 CONCEPTNET : meeting_people 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : flirting 】
usedfor 【 CONCEPTNET : meeting_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : become_aroused 】
hasprerequisite 【 CONCEPTNET : copulate 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : become_aroused 】
hasprerequisite 【 CONCEPTNET : copulate 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : become_aroused 】
hassubevent 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : blushing 】
hassubevent 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : catch_cold 】
hassubevent 【 CONCEPTNET : walk_in_rain 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : catch_cold 】
motivatedbygoal 【 CONCEPTNET : walk_in_rain 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : close_eyes 】
hasfirstsubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : close_eyes 】
hasfirstsubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : close_eyes 】
haslastsubevent 【 CONCEPTNET : hear_music 】
motivatedbygoal 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : close_eyes 】
haslastsubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : close_eyes 】
haslastsubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : close_eyes 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : close_eyes 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : close_eyes 】
hassubevent 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : closing_eyes 】
hassubevent 【 CONCEPTNET : remembering 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : closing_eyes 】
hassubevent 【 CONCEPTNET : remembering 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : embrace 】
hasprerequisite 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : embrace 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : embrace 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : embrace 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
causes 【 CONCEPTNET : enjoying_day 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
causes 【 CONCEPTNET : enjoying_day 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
haslastsubevent 【 CONCEPTNET : see_idea_become_reality 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : celebrate 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : laugh 】
distinctfrom 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : see_favorite_show 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : see_favorite_show 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : see_favorite_show 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : tasting_sweet 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
hassubevent 【 CONCEPTNET : tasting_sweet 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
motivatedbygoal 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : feel_happy 】
motivatedbygoal 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : get_caught 】
hassubevent 【 CONCEPTNET : lie 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : get_sick 】
haslastsubevent 【 CONCEPTNET : stay_healthy 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : get_sick 】
hassubevent 【 CONCEPTNET : performing 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : good_feeling 】
causes 【 CONCEPTNET : making_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
capableof 【 CONCEPTNET : lift_spirits 】
capableof 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
causes 【 CONCEPTNET : thanking 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
causes 【 CONCEPTNET : thanking 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
hasfirstsubevent 【 CONCEPTNET : agree_with 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
hasfirstsubevent 【 CONCEPTNET : agree_with 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
haslastsubevent 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
hassubevent 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
hassubevent 【 CONCEPTNET : meet_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
hassubevent 【 CONCEPTNET : meeting_friend 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
hassubevent 【 CONCEPTNET : thanking 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
hassubevent 【 CONCEPTNET : thanking 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX gives PersonY a hug 】
oWant 【 ATOMIC_INFER : smile at personx 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX gives PersonY a hug 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX gives ___ a hug 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX gives ___ a hug 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX hugs PersonY back 】
oEffect 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX hugs PersonY back 】
oWant 【 ATOMIC_INFER : to smile back 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX hugs PersonY back 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX hugs PersonY back 】
xWant 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX hugs PersonY tight 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX hugs PersonY's mom 】
oEffect 【 ATOMIC_INFER : persony's mom smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX hugs PersonY's mom 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX hugs PersonY's mom 】
xWant 【 ATOMIC_INFER : to get a smile from persony's mom. 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_EVENT : PersonX pulls PersonY into a hug 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_INFER : persony hugs personx 】
oEffect 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_INFER : to hug persony 】
xWant 【 ATOMIC_EVENT : PersonX smiles back at PersonY 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : hug 】
-> 【 ATOMIC_INFER : hugs persony 】
xEffect 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : kissed 】
-> 【 ATOMIC_INFER : kissed 】
xEffect 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
causes 【 CONCEPTNET : remembering 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
causes 【 CONCEPTNET : remembering 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
distinctfrom 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasfirstsubevent 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasfirstsubevent 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasfirstsubevent 【 CONCEPTNET : express_how_funny 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasfirstsubevent 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasfirstsubevent 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasfirstsubevent 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
haslastsubevent 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
haslastsubevent 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
haslastsubevent 【 CONCEPTNET : express_how_funny 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasprerequisite 【 CONCEPTNET : express_how_funny 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasprerequisite 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasprerequisite 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hasprerequisite 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : enjoying_film 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : express_how_funny 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : get_good_grade 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : get_good_grade 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : getting_physical_activity 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : having_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : performing 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : see_favorite_show 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : see_favorite_show 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : see_favorite_show 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : surprising 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
hassubevent 【 CONCEPTNET : talking_to 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
isa 【 CONCEPTNET : facial_expression 】
isa 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
isa 【 CONCEPTNET : facial_expression 】
isa 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
motivatedbygoal 【 CONCEPTNET : happy 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
motivatedbygoal 【 CONCEPTNET : happy 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
motivatedbygoal 【 CONCEPTNET : happy 】
motivatedbygoal 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
motivatedbygoal 【 CONCEPTNET : see_favorite_show 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
motivatedbygoal 【 CONCEPTNET : see_favorite_show 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
motivatedbygoal 【 CONCEPTNET : see_favorite_show 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX has a good laugh 】
xWant 【 ATOMIC_INFER : smile at someone 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX has the last laugh 】
xEffect 【 ATOMIC_INFER : smiles big. 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs , cried 】
xWant 【 ATOMIC_INFER : to smile again 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs PersonY's asses 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs a lot 】
xEffect 【 ATOMIC_INFER : smiles a lot 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs and talking 】
oEffect 【 ATOMIC_INFER : smiles and laughs too 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs and talking 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs and talking 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs and talking 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs and talking 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs and told 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs hard 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs heartily 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs out loud 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX laughs so hard 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX makes PersonY laugh 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX makes PersonY laugh 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX makes PersonY laugh 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX makes PersonY laugh 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX makes PersonY laugh 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX makes PersonY's laugh 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX starts to laugh 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX starts to laugh 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX tries not to laugh 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_EVENT : PersonX tries not to laugh 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : laughs out loud 】
oEffect 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : laughs 】
oEffect 【 ATOMIC_EVENT : PersonX cracks a smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : laughs 】
xEffect 【 ATOMIC_EVENT : PersonX cracks a smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : laughs 】
xEffect 【 ATOMIC_EVENT : PersonX smiles broadly 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : laughs 】
xEffect 【 ATOMIC_EVENT : PersonX smiles happily 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : they laugh 】
xEffect 【 ATOMIC_EVENT : PersonX smiles broadly 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : to laugh 】
xWant 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : to laugh 】
oWant 【 ATOMIC_EVENT : PersonX makes PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : to laugh 】
oWant 【 ATOMIC_EVENT : PersonX smiles broadly 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : to laugh 】
xWant 【 ATOMIC_EVENT : PersonX smiles broadly 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : laugh 】
-> 【 ATOMIC_INFER : to laugh 】
xWant 【 ATOMIC_EVENT : PersonX smiles broadly 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : make_love 】
hasfirstsubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : make_love 】
hasfirstsubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : make_love 】
hasprerequisite 【 CONCEPTNET : copulate 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : make_love 】
hasprerequisite 【 CONCEPTNET : copulate 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : sexual_arousal 】
causesdesire 【 CONCEPTNET : copulate 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : sexual_arousal 】
causesdesire 【 CONCEPTNET : copulate 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : sexual_arousal 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : sexual_arousal 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : love_another 】
hasfirstsubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : love_another 】
hasfirstsubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : loving_another 】
hassubevent 【 CONCEPTNET : happy 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : loving_another 】
hassubevent 【 CONCEPTNET : happy 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : loving_another 】
hassubevent 【 CONCEPTNET : happy 】
motivatedbygoal 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : loving_another 】
hassubevent 【 CONCEPTNET : helping 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : loving_another 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : loving_another 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : loving_else 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : loving_else 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : seeing_movie 】
hassubevent 【 CONCEPTNET : entertain 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : seeing_movie 】
hassubevent 【 CONCEPTNET : entertain 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
hassubevent 【 CONCEPTNET : seeing_movie 】
usedfor 【 CONCEPTNET : having_good_time 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
isa 【 CONCEPTNET : pleasant_sensation 】
causes 【 CONCEPTNET : tasting_sweet 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
isa 【 CONCEPTNET : pleasant_sensation 】
causes 【 CONCEPTNET : tasting_sweet 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
isa 【 CONCEPTNET : human_activity 】
isa 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
isa 【 CONCEPTNET : human_activity 】
isa 【 CONCEPTNET : pretending 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
isa 【 CONCEPTNET : intelligent_agent_activity 】
isa 【 CONCEPTNET : pretending 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : affection 】
causes 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : affection 】
isa 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : bonding 】
usedfor 【 CONCEPTNET : making_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : foreplay 】
hasfirstsubevent 【 CONCEPTNET : copulate 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : foreplay 】
hasfirstsubevent 【 CONCEPTNET : copulate 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
causes 【 CONCEPTNET : making_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
causes 【 CONCEPTNET : talking_to 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
causesdesire 【 CONCEPTNET : agree_with 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
causesdesire 【 CONCEPTNET : agree_with 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
motivatedbygoal 【 CONCEPTNET : socialize 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
motivatedbygoal 【 CONCEPTNET : socialize 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
usedfor 【 CONCEPTNET : meeting_people 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
usedfor 【 CONCEPTNET : meeting_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : friendship 】
-> 【 ATOMIC_INFER : friendship 】
xIntent 【 ATOMIC_EVENT : PersonX smiles upon PersonY 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : eating_ice_cream 】

hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : enjoying_film 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : getting_physical_activity 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : going_to_performance 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
causes 【 CONCEPTNET : pretending 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
causesdesire 【 CONCEPTNET : express_how_funny 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
causesdesire 【 CONCEPTNET : socialize 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
causesdesire 【 CONCEPTNET : socialize 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
hasprerequisite 【 CONCEPTNET : howling_with_laughter 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
hasproperty 【 CONCEPTNET : killing_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
hasproperty 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
hasproperty 【 CONCEPTNET : making_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
hassubevent 【 CONCEPTNET : chat_with_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
hassubevent 【 CONCEPTNET : flirt 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
hassubevent 【 CONCEPTNET : flirt 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
hassubevent 【 CONCEPTNET : flirt 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
isa 【 CONCEPTNET : listen_to_radio 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
isa 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
motivatedbygoal 【 CONCEPTNET : have_fun 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : dreaming 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : eating_ice_cream 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : enjoying_film 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : flirting 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : getting_physical_activity 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : going_to_performance 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : hiking 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : howling_with_laughter 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : listening_to_music 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : surprising 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : talking_to 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : winning_baseball_game 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has a lot of fun playing 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has a ton of fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has fun playing 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has fun playing 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has fun with PersonX's friends 】
xEffect 【 ATOMIC_INFER : personx smiles from  fun. 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has fun with PersonY's friends 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has great fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has much fun 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has so much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has so much fun playing 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX has too much fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX is having a lot of fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX is so much fun 】
xWant 【 ATOMIC_INFER : make people smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX looks fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX makes fun of PersonY's 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_EVENT : PersonX sounds fun 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : fun 】
-> 【 ATOMIC_INFER : to have fun 】
oWant 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
atlocation 【 CONCEPTNET : human 】
capableof 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causes 【 CONCEPTNET : meeting_people 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causes 【 CONCEPTNET : meeting_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : entertain 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : entertain 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : flirt 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : flirt 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : flirt 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : hear_singing 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : lie 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : make_friends 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : make_friends 】
usedfor 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : meet_friend 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
causesdesire 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
distinctfrom 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : make_friends 】
hasprerequisite 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : make_friends 】
usedfor 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
hasprerequisite 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
hassubevent 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
hassubevent 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
mannerof 【 CONCEPTNET : like 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
motivatedbygoal 【 CONCEPTNET : enjoy_company_of_friends 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
motivatedbygoal 【 CONCEPTNET : enjoy_company_of_friends 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
motivatedbygoal 【 CONCEPTNET : meet_girls 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
motivatedbygoal 【 CONCEPTNET : please_parents 】
hasfirstsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
usedfor 【 CONCEPTNET : killing_people 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
usedfor 【 CONCEPTNET : remembering 】
causes 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
usedfor 【 CONCEPTNET : remembering 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX confesses PersonX's love 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX confesses PersonX's love 】
xEffect 【 ATOMIC_INFER : gets smiled at 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's ___ as PersonX's bodies 】
xEffect 【 ATOMIC_INFER : smiles with joy 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's beard 】
xEffect 【 ATOMIC_INFER : smiles in satisfaction 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's beard 】
xEffect 【 ATOMIC_INFER : personx smiles at themself in the mirror 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's beard 】
xWant 【 ATOMIC_INFER : smile at self 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's car 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's mother 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's new job 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonX's trip 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY back 】
xEffect 【 ATOMIC_INFER : they smile inadvertently 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY very much 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's car 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's dog 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's motorcycle 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's motorcycle 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's neighbor 】
xEffect 【 ATOMIC_INFER : personx smiles at persony's neighbor 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's new hair 】
oEffect 【 ATOMIC_INFER : they smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's new hair 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's new hair 】
xEffect 【 ATOMIC_INFER : he smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's new home 】
oEffect 【 ATOMIC_INFER : persony smiles and has sensations of pride. 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves PersonY's work 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves ___ above all things 】
xEffect 【 ATOMIC_INFER : personx smiles at god's presence 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves ___ dearly 】
xEffect 【 ATOMIC_INFER : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves ___ so much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves ___ very much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves coffee 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves every minute of it 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves gymnastics 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves helping people 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves helping people 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves it very much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves oranges 】
xEffect 【 ATOMIC_INFER : smiles thinking about oranges 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves playing video games 】
xEffect 【 ATOMIC_INFER : personx smiles at the videogame 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves riding PersonX's bike 】
xEffect 【 ATOMIC_INFER : smiles with joy 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves spending time 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the car 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the car 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the dog 】
xEffect 【 ATOMIC_INFER : smiles at the dog 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the dress 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the experience 】
xEffect 【 ATOMIC_INFER : has a wide smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the gift 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the meal 】
xEffect 【 ATOMIC_INFER : personx smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the pictures 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the pictures 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the rain 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the show 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the song 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves the view 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves to draw 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves to go fishing 】
xEffect 【 ATOMIC_INFER : smiles when going fishing 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves to go fishing 】
xEffect 【 ATOMIC_INFER : smiles when he catches a fish 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX loves very much 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX shows PersonY's love 】
oEffect 【 ATOMIC_INFER : persony smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX shows PersonY's love 】
xEffect 【 ATOMIC_INFER : receives a smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】
-> 【 ATOMIC_EVENT : PersonX stills loves PersonY 】
oEffect 【 ATOMIC_INFER : smiles back 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : love 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : mouth 】
hasprerequisite 【 CONCEPTNET : tasting_sweet 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : mouth 】
usedfor 【 CONCEPTNET : kiss 】
haslastsubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : mouth 】
usedfor 【 CONCEPTNET : kiss 】
hassubevent 【 CONCEPTNET : smile 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : mouth 】
-> 【 ATOMIC_EVENT : PersonX pops ___ in PersonX's mouth 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
usedfor 【 CONCEPTNET : neck 】
-> 【 ATOMIC_EVENT : PersonX cranes PersonY's neck 】
oEffect 【 ATOMIC_INFER : persony smiles with relief 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
oWant 【 ATOMIC_INFER : to talk to personx 】
oWant 【 ATOMIC_EVENT : PersonX smiles upon PersonY 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xAttr 【 ATOMIC_INFER : thoughtful 】
xAttr 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX cracks a smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX gives PersonY a smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX gives PersonY a smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX gives PersonY a smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX gives PersonY a smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX has a smile on PersonY's face 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX looks at PersonY with a smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX looks at PersonY with a smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX makes PersonY smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX makes PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX makes PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX makes PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX makes PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX puts a smile on my face 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX sees PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX sees PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX sees PersonY's smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX smiles PersonX's smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX smiles back 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX smiles back 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX smiles broadly 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX smiles broadly 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX smiles happily 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX smiles happily 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX smiles happily 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX smiles upon PersonY 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX smiles upon PersonY 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX smiles upon PersonY 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_EVENT : PersonX stops kissing PersonY 】
xWant 【 ATOMIC_INFER : to leave 】
oWant 【 ATOMIC_EVENT : PersonX smiles upon PersonY 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_INFER : to continue kissing 】
xWant 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_INFER : to continue kissing 】
xWant 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
oEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_INFER : to continue kissing 】
xWant 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
oWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_INFER : to continue kissing 】
xWant 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
xEffect 【 ATOMIC_INFER : smiles 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_INFER : to continue kissing 】
xWant 【 ATOMIC_EVENT : PersonX kisses PersonY's forehead 】
xWant 【 ATOMIC_INFER : to smile 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_INFER : to keep kissing persony 】
xWant 【 ATOMIC_EVENT : PersonX kisses PersonY on the lips 】
oEffect 【 ATOMIC_INFER : persony smiles at personx 】

-> 【 CONCEPTNET : kissing 】
-> 【 ATOMIC_INFER : like kissing is a good way to show admiration 】
xReact 【 ATOMIC_EVENT : PersonX gives ___ a kiss 】
oEffect 【 ATOMIC_INFER : smiles 】

In [52]:
rel = kb.search_path_byEntity("ocean","castle",2)
print(len(rel))
for r in rel:
    for d in r:
        print(d['rel_w_parent'] if d['rel_w_parent'] else "->", "【", d["kb_type"].upper(), ":", d['key'], "】")
    print(" ")

9
-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : build sand castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : personx builds a sand castle. 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : to build sand castles 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : makes sand castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : they take a picture of their sand castles and moat 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : to build a sand castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : builds a sand castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : making a sand castle 】

-> 【 CONCEPTNET : ocean 】
usedfor 【 CONCEPTNET : travel 】
-> 【 ATOMIC_INFER : to travel to the castle 】

In [14]:
rel = kb.search_path_byEntity("ocean","castle",3)
print(len(rel))
for r in rel:
    for d in r:
        print(d['rel_w_parent'] if d['rel_w_parent'] else "->", "【", d["kb_type"].upper(), ":", d['key'], "】")
    print(" ")

49
-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : creature 】
atlocation 【 CONCEPTNET : fairy_tale 】
atlocation 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : fungus 】
atlocation 【 CONCEPTNET : cellar 】
atlocation 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : jellyfish 】
atlocation 【 CONCEPTNET : book 】
isa 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : beach 】
-> 【 ATOMIC_EVENT : PersonX drives to the beach 】
xEffect 【 ATOMIC_INFER : build sand castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : beach 】
-> 【 ATOMIC_EVENT : PersonX goes to the beach with PersonX's friends 】
xEffect 【 ATOMIC_INFER : personx builds a sand castle. 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : beach 】
-> 【 ATOMIC_EVENT : PersonX goes to the beach with PersonY's friends 】
xEffect 【 ATOMIC_INFER : builds a sand castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : beach 】
-> 【 ATOMIC_EVENT : PersonX takes PersonY to the beach 】
xWant 【 ATOMIC_INFER : to build sand castles 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : earth 】
partof 【 CONCEPTNET : europe 】
atlocation 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : lake 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : movie 】
atlocation 【 CONCEPTNET : knight 】
atlocation 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : movie 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_EVENT : PersonX builds sand castles 】
xEffect 【 ATOMIC_INFER : they build a moat around the castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_EVENT : PersonX builds sand castles 】
xEffect 【 ATOMIC_INFER : they take a picture of their sand castles and moat 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_EVENT : PersonX gets sand 】
xEffect 【 ATOMIC_INFER : builds a sand castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_EVENT : PersonX gets sand 】
xWant 【 ATOMIC_INFER : to build a castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_EVENT : PersonX pounds sand 】
xEffect 【 ATOMIC_INFER : makes sand castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : sand 】
-> 【 ATOMIC_INFER : to put sand on air plane 】
xNeed 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : vessel 】
atlocation 【 CONCEPTNET : home 】
isa 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
atlocation 【 CONCEPTNET : vessel 】
atlocation 【 CONCEPTNET : home 】
isa 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
distinctfrom 【 CONCEPTNET : lake 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
hasprerequisite 【 CONCEPTNET : surfing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
isa 【 CONCEPTNET : sailing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
usedfor 【 CONCEPTNET : diving 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
usedfor 【 CONCEPTNET : fishing 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
usedfor 【 CONCEPTNET : relax 】
usedfor 【 CONCEPTNET : home 】
isa 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
usedfor 【 CONCEPTNET : relax 】
usedfor 【 CONCEPTNET : home 】
isa 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
usedfor 【 CONCEPTNET : sailing 】
hasproperty 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
usedfor 【 CONCEPTNET : swimming 】
usedfor 【 CONCEPTNET : fun 】
usedfor 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
usedfor 【 CONCEPTNET : travel 】
usedfor 【 CONCEPTNET : passageway 】
atlocation 【 CONCEPTNET : castle 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX lives by the ocean 】
xAttr 【 ATOMIC_INFER : creative 】
xAttr 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX lives by the ocean 】
xAttr 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX lives by the ocean 】
xAttr 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX lives by the ocean 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX lives by the ocean 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX lives by the ocean 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX lives by the ocean 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX sees the ocean 】
xAttr 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX sees the ocean 】
xAttr 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX takes ___ to the ocean 】
oReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX takes ___ to the ocean 】
oReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX takes ___ to the ocean 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_EVENT : PersonX takes ___ to the ocean 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX builds castles in the air 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_INFER : swims in ocean 】
xEffect 【 ATOMIC_EVENT : PersonX drives to the beach 】
xEffect 【 ATOMIC_INFER : build sand castle 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_INFER : swims in ocean 】
oEffect 【 ATOMIC_EVENT : PersonX goes to the beach with PersonY's friends 】
xEffect 【 ATOMIC_INFER : builds a sand castle 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_INFER : swims in ocean 】
xEffect 【 ATOMIC_EVENT : PersonX goes to the beach with PersonY's friends 】
xEffect 【 ATOMIC_INFER : builds a sand castle 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_INFER : to jump in the ocean 】
xWant 【 ATOMIC_EVENT : PersonX gets sand 】
xEffect 【 ATOMIC_INFER : builds a sand castle 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_INFER : to jump in the ocean 】
xWant 【 ATOMIC_EVENT : PersonX gets sand 】
xWant 【 ATOMIC_INFER : to build a castle 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_INFER : to store as much oxygen for the dive into the ocean. 】
xIntent 【 ATOMIC_EVENT : PersonX fills PersonX's ___ with air 】
xNeed 【 ATOMIC_INFER : to rent a jumping castle for the children 】

-> 【 CONCEPTNET : ocean 】
-> 【 ATOMIC_INFER : to swim in the ocean 】
xIntent 【 ATOMIC_EVENT : PersonX drives to the beach 】
xEffect 【 ATOMIC_INFER : build sand castle 】

In [61]:
#kb.ConceptNet['ocean']
kb.ATOMIC_Events['PersonX lives by the ocean']

{'atomic_infer': {'oEffect': ['have to relocate because of the storm',
   "can't visit during a storm."],
  'oReact': [],
  'oWant': ['to go to the beach.', 'to go swimming.'],
  'xAttr': ['adventurous',
   'independent',
   'artistic',
   'creative',
   'serene',
   'happy',
   'relaxed',
   'sucessful'],
  'xEffect': ['house gets flooded during the storm',
   'and they have to move',
   'has to get flood insurance',
   'gets an ocean breeze',
   'smells the ocean water'],
  'xIntent': ['a good view',
   'to be able to swim',
   'to enjoy the area',
   'to be relaxed',
   'to be happy',
   'to be living near the beach and enjoys surfing',
   'to be close to nature'],
  'xNeed': ['to move near the ocean',
   'to buy a house near the ocean',
   'to buy a house.',
   'to move into the house.',
   'to have bought a house by the ocean',
   'to have a lot of money'],
  'xReact': ['relaxed',
   'excited',
   'happy',
   'content',
   'relaxed',
   'happy',
   'joyful',
   'relaxed'],
  'xWant': ['to retire near the ocean',
   'to move somewhere else',
   'to have friends over.',
   'to have a beach barbeque.',
   'to go fishing',
   'to run on the beach every day'],
  'prefix': ['lives', 'ocean']},
 'conceptnet': {'life', 'ocean'}}

In [59]:
rel = kb.search_path_byEntity("kissing","smile",3)
for path in rel:
    print(list(path))

[('conceptnet', 'kissing'), ('conceptnet', 'lovers'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'lovers'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'lovers'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'lovers'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'going_see_film'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'arousal'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'arousal'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'getting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'meeting_friend'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'opening_gift'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'being_happy'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'catch_cold'), ('conceptnet', 'walk_in_rain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'catch_cold'), ('conceptnet', 'walk_in_rain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'catch_cold'), ('conceptnet', 'walk_in_rain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'catch_cold'), ('conceptnet', 'walk_in_rain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('conceptnet', 'hearing_crowd_go_mad'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('conceptnet', 'hearing_crowd_go_mad'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('conceptnet', 'meeting_friend'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('conceptnet', 'opening_gift'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles from excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'they smile with excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles with excitement of the new game'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles in excitement of the new layout of the course'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'persony smiles in excitement'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', "persony's husband smiles with excitement"), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'excitement'), ('atomic_infer', 'personx smiles with excitement.'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'attending_classical_concert'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'getting_good_grade'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'getting_physical_activity'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'helping'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'howling_with_laughter'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feeling_good'), ('conceptnet', 'looking_better'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'attending_classical_concert'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'enjoying_film'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'getting_good_grade'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'going_to_performance'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'helping'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'howling_with_laughter'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'looking_better'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'making_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'meeting_friend'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'opening_gift'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'performing'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'reading_letter'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'reading_letter'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'serving_customers'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'winning_baseball_game'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'buying_shirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'receiving_degree'), ('conceptnet', 'smile')]

[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'personx smiles with happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles in happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smile from happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'personx smiles from happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles with happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles with happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles with happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles with happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'happiness'), ('atomic_infer', 'smiles from happiness'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'taste_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('conceptnet', 'taste_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('atomic_infer', 'smiles because he or she likes seeing people making an effort'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('atomic_infer', 'they like the brushing and smile in return'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'like'), ('atomic_infer', 'starts to smile if he likes persony'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'lipstick_on_cheek'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'lipstick_on_cheek'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'human'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'meeting_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'meeting_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'hear_singing'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'lie'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'meet_friend'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'meet_girls'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'killing_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]

[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'human'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'meeting_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'meeting_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'hear_singing'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'lie'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'meet_friend'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'meet_girls'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'killing_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasurable'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasurable'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasurable'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'going_to_performance'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'opening_gift'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'open_gift'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'make_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'attending_classical_concert'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasure'), ('conceptnet', 'getting_physical_activity'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sex'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sex'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sex'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sex'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sex'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sex'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sexual_excitement'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'smeared_lipstick'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'smeared_lipstick'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'strong_feelings'), ('conceptnet', 'hear_singing'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sleighing_ride'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sleighing_ride'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sleighing_ride'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sleighing_ride'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'enjoying_film'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'kiss'), ('conceptnet', 'surprising'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'partner'), ('conceptnet', 'look_better'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'partner'), ('conceptnet', 'look_better'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'partner'), ('conceptnet', 'meet_girls'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'two_people'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'enjoyable'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'enjoyable'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'enjoyable'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'enjoyable'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'enjoyable'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'enjoying_film'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'enjoying_film'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'getting_physical_activity'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'getting_physical_activity'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'going_to_performance'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'going_to_performance'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'pretending'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'express_how_funny'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'socialize'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'socialize'), ('conceptnet', 'smile')]

[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'howling_with_laughter'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'howling_with_laughter'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'killing_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'making_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'chat_with_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'listen_to_radio'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'dreaming'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'hiking'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'surprising'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'talking_to'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'winning_baseball_game'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('atomic_infer', 'personx smiles from  fun.'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('atomic_infer', 'smiles thinking of his fun attitude'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'enjoying_film'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'enjoying_film'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'getting_physical_activity'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'getting_physical_activity'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'going_to_performance'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'going_to_performance'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'pretending'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'express_how_funny'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'socialize'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'socialize'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'howling_with_laughter'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'howling_with_laughter'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'killing_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'making_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'chat_with_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'flirt'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'listen_to_radio'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'dreaming'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'hiking'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'surprising'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'talking_to'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('conceptnet', 'winning_baseball_game'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('atomic_infer', 'personx smiles from  fun.'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'fun'), ('atomic_infer', 'smiles thinking of his fun attitude'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('conceptnet', 'helping'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('conceptnet', 'human'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('conceptnet', 'killing_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles from doing something good'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles from doing something good'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles from doing something good'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles from doing something good'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'to smile endlessly because it was a good show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles to personx when he receives the goods'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'personx smiles after giving a good pep talk to persony about boys'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles at their good fortune'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'to smile and tell people he got a good deal'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles from the good reply'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'feels good for making the smile'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles because he/she did a good job'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles because it tastes good'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'put on a good smile for a picture'), ('conceptnet', 'smile')]

[('conceptnet', 'kissing'), ('conceptnet', 'good'), ('atomic_infer', 'smiles at good shot'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'winning_baseball_game'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'having_good_time'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'having_good_time'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'celebrating'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'date'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'date'), ('atomic_infer', "to smile because they didn't expect to be asked on a date"), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'date'), ('atomic_infer', "persony's date smiles at personx"), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'dating'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'dating'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'dating'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'dating'), ('conceptnet', 'improving_image'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'flirting'), ('conceptnet', 'meet_girls'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'flirting'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'flirting'), ('conceptnet', 'meeting_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'flirting'), ('conceptnet', 'meeting_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'become_aroused'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'become_aroused'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'become_aroused'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'blushing'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'close_eyes'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'close_eyes'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'close_eyes'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'close_eyes'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'close_eyes'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'close_eyes'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'close_eyes'), ('conceptnet', 'hear_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'close_eyes'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'closing_eyes'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'closing_eyes'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'embrace'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'embrace'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'embrace'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'embrace'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'enjoying_day'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'see_idea_become_reality'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'celebrate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'laugh'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'laugh'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'feel_happy'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'get_caught'), ('conceptnet', 'lie'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'get_sick'), ('conceptnet', 'stay_healthy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'get_sick'), ('conceptnet', 'performing'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'good_feeling'), ('conceptnet', 'making_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'lift_spirits'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'thanking'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'thanking'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'thanking'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'thanking'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'agree_with'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'agree_with'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'please_parents'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'meet_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('conceptnet', 'meeting_friend'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'hug'), ('atomic_infer', 'smile and hug'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'enjoy_company_of_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'express_how_funny'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'express_how_funny'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'express_how_funny'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'express_how_funny'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'have_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'enjoying_film'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'get_good_grade'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'get_good_grade'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'getting_physical_activity'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'having_fun'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'performing'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'see_favorite_show'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'surprising'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'talking_to'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'facial_expression'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'facial_expression'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]

[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'laughs and smiles'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'to laugh and smile'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'to laugh and smile'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'to laugh and smile'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'to laugh and smile'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'they laughed and smiled'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'smiles and laughs too'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'laugh'), ('atomic_infer', 'persony smiles and laughs at personx'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'make_love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'make_love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'make_love'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'make_love'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sexual_arousal'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sexual_arousal'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sexual_arousal'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'sexual_arousal'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love_another'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'love_another'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'loving_another'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'loving_another'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'loving_another'), ('conceptnet', 'happy'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'loving_another'), ('conceptnet', 'helping'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'loving_another'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'loving_another'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'loving_else'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'loving_else'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'seeing_movie'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'seeing_movie'), ('conceptnet', 'entertain'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'seeing_movie'), ('conceptnet', 'having_good_time'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasant_sensation'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'pleasant_sensation'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'human_activity'), ('conceptnet', 'listening_to_music'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'human_activity'), ('conceptnet', 'pretending'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'intelligent_agent_activity'), ('conceptnet', 'pretending'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'affection'), ('conceptnet', 'flirting'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'affection'), ('conceptnet', 'like'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'bonding'), ('conceptnet', 'making_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'foreplay'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'foreplay'), ('conceptnet', 'copulate'), ('conceptnet', 'smile')]

[('conceptnet', 'kissing'), ('conceptnet', 'friendship'), ('conceptnet', 'making_friends'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'friendship'), ('conceptnet', 'talking_to'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'friendship'), ('conceptnet', 'agree_with'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'friendship'), ('conceptnet', 'agree_with'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'friendship'), ('conceptnet', 'socialize'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'friendship'), ('conceptnet', 'socialize'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'friendship'), ('conceptnet', 'meeting_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'friendship'), ('conceptnet', 'meeting_people'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'people_in_love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'people_in_love'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'remembering'), ('conceptnet', 'laugh'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'remembering'), ('conceptnet', 'laugh'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'remembering'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'reminding'), ('conceptnet', 'helping'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'mouth'), ('conceptnet', 'human'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'mouth'), ('conceptnet', 'eating_ice_cream'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'mouth'), ('conceptnet', 'talking_to'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'mouth'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'mouth'), ('conceptnet', 'tasting_sweet'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'mouth'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('conceptnet', 'mouth'), ('conceptnet', 'kiss'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('atomic_infer', 'to thank personx for arse kissing'), ('conceptnet', 'thank'), ('conceptnet', 'smile')]
[('conceptnet', 'kissing'), ('atomic_infer', 'to thank personx for arse kissing'), ('conceptnet', 'thank'), ('conceptnet', 'smile')]

In [55]:
for path in rel:
    print(list(path))

In [65]:
import pickle

In [141]:
data = pickle.load(open("SocialIQa/socialIQa_v1.4_trn_s11_knowledgePath_all.pickle",'rb'))

In [110]:
len(data[2994])

53

In [142]:
query_count_for_each_qa = []
path_count_for_each_qa = []
path_count_for_each_query = []

for idx, qa_pair in enumerate(data):
    if qa_pair:
        query_count_for_each_qa.append(len(qa_pair))
        path_count_for_each_qa.append(0)
    else:
        print("missed:",idx)
    for query in qa_pair:
        path_count_for_each_qa[-1] += len(query)
        path_count_for_each_query.append(len(query))

## Extract meaningful paths cross CKB

In [8]:
import random

print(random.randint(3, 9))

4

In [55]:
kb.ConceptNet['study']

{'atomic_event': ['PersonX applies ___ to the study',
  'PersonX applies the ___ to the study',
  "PersonX completes PersonX's studies",
  "PersonX continues PersonX's studies",
  "PersonX devotes PersonX's ___ to the study",
  'PersonX devotes ___ to the study',
  "PersonX finishes PersonX's studies",
  'PersonX forgets to study',
  'PersonX helps PersonY study',
  "PersonX helps PersonY's study",
  'PersonX makes PersonY study',
  'PersonX needs to study',
  "PersonX pursues PersonX's studies",
  'PersonX starts to study',
  "PersonX studies PersonY's face",
  'PersonX studies ___ at the university',
  'PersonX studies ___ at university',
  'PersonX studies ___ carefully',
  'PersonX studies ___ every night',
  'PersonX studies ___ for years',
  'PersonX studies ___ in college',
  'PersonX studies ___ long',
  'PersonX studies a lot',
  'PersonX studies abroad',
  'PersonX studies all day',
  'PersonX studies all night',
  'PersonX studies all week',
  'PersonX studies as hard',
  'PersonX studies as much',
  'PersonX studies as much as PersonY could',
  'PersonX studies carefully the ___',
  'PersonX studies day and night',
  'PersonX studies enough',
  'PersonX studies every ___',
  'PersonX studies every day',
  'PersonX studies every night',
  'PersonX studies extra',
  'PersonX studies extra hard',
  "PersonX studies for PersonX's exam",
  "PersonX studies for PersonX's math test",
  "PersonX studies for PersonX's test",
  'PersonX studies for a quiz',
  'PersonX studies for a test',
  'PersonX studies for a week',
  'PersonX studies for an exam',
  'PersonX studies for the test',
  'PersonX studies for weeks',
  'PersonX studies hard',
  'PersonX studies hard ___',
  'PersonX studies hard in school',
  'PersonX studies in detail the ___',
  'PersonX studies in the library',
  'PersonX studies really hard',
  'PersonX studies science',
  'PersonX studies the ___ carefully',
  'PersonX studies the ___ in detail',
  'PersonX studies very hard',
  'PersonX studies very hard for the test',
  'PersonX studies very hard in school',
  'PersonX tries to study'],
 'conceptnet': [{'rel': 'atlocation', 'tail': 'armchair', 'direction': 1},
  {'rel': 'atlocation', 'tail': 'bookcase', 'direction': 1},
  {'rel': 'atlocation', 'tail': 'desk', 'direction': 1},
  {'rel': 'atlocation', 'tail': 'desk_tray', 'direction': 1},
  {'rel': 'atlocation', 'tail': 'poet', 'direction': 1},
  {'rel': 'atlocation', 'tail': 'big_house', 'direction': 0},
  {'rel': 'atlocation', 'tail': 'bust_of_famous_author', 'direction': 0},
  {'rel': 'atlocation', 'tail': 'journal', 'direction': 0},
  {'rel': 'atlocation', 'tail': 'large_house', 'direction': 0},
  {'rel': 'atlocation', 'tail': 'mansion', 'direction': 0},
  {'rel': 'atlocation', 'tail': 'maonr_house', 'direction': 0},
  {'rel': 'atlocation', 'tail': 'quiet_part_of_house', 'direction': 0},
  {'rel': 'atlocation', 'tail': 'schools', 'direction': 0},
  {'rel': 'atlocation', 'tail': 'scientific_library', 'direction': 0},
  {'rel': 'capableof', 'tail': 'student', 'direction': 1},
  {'rel': 'capableof', 'tail': 'students', 'direction': 1},
  {'rel': 'capableof', 'tail': 'bring_understanding', 'direction': 0},
  {'rel': 'capableof', 'tail': 'prove_to_wrong', 'direction': 0},
  {'rel': 'causes', 'tail': 'bethink', 'direction': 1},
  {'rel': 'causes', 'tail': 'knowledge', 'direction': 0},
  {'rel': 'causes', 'tail': 'taking_exam', 'direction': 1},
  {'rel': 'causesdesire', 'tail': 'ambition', 'direction': 1},
  {'rel': 'causesdesire',
   'tail': 'desire_to_learn_new_language',
   'direction': 1},
  {'rel': 'causesdesire', 'tail': 'interest_in_subject', 'direction': 1},
  {'rel': 'causesdesire', 'tail': 'motivation', 'direction': 1},
  {'rel': 'causesdesire', 'tail': 'need_to_pass_exam', 'direction': 1},
  {'rel': 'causesdesire', 'tail': 'running_out_of_weed', 'direction': 1},
  {'rel': 'causesdesire', 'tail': 'sex_ed', 'direction': 1},
  {'rel': 'causesdesire', 'tail': 'teacher', 'direction': 1},
  {'rel': 'desires', 'tail': 'person', 'direction': 1},
  {'rel': 'entails', 'tail': 'read', 'direction': 0},
  {'rel': 'hasa', 'tail': 'doctors', 'direction': 1},
  {'rel': 'hasa', 'tail': 'many_books', 'direction': 0},
  {'rel': 'hasfirstsubevent', 'tail': 'analyse', 'direction': 1},
  {'rel': 'hasfirstsubevent', 'tail': 'memorize', 'direction': 1},
  {'rel': 'hasfirstsubevent', 'tail': 'pass_course', 'direction': 1},
  {'rel': 'hasfirstsubevent', 'tail': 'see_new', 'direction': 1},
  {'rel': 'hasfirstsubevent', 'tail': 'concentrate', 'direction': 0},
  {'rel': 'hasfirstsubevent', 'tail': 'open_book', 'direction': 0},
  {'rel': 'hasfirstsubevent', 'tail': 'prepare_snack', 'direction': 0},
  {'rel': 'hasfirstsubevent', 'tail': 'read', 'direction': 0},
  {'rel': 'hasfirstsubevent', 'tail': 'read_books', 'direction': 0},
  {'rel': 'hasfirstsubevent', 'tail': 'take_finals', 'direction': 1},
  {'rel': 'hasfirstsubevent', 'tail': 'take_midterm', 'direction': 1},
  {'rel': 'haslastsubevent', 'tail': 'close_book', 'direction': 0},
  {'rel': 'haslastsubevent', 'tail': 'forget_everything', 'direction': 0},
  {'rel': 'haslastsubevent', 'tail': 'graduate', 'direction': 0},
  {'rel': 'haslastsubevent', 'tail': 'put_book_down', 'direction': 0},
  {'rel': 'haslastsubevent', 'tail': 'review_notes', 'direction': 0},
  {'rel': 'haslastsubevent', 'tail': 'sit_at_desk', 'direction': 0},
  {'rel': 'haslastsubevent', 'tail': 'watch_tv_at_same_time', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'act_in_play', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'analyse', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'answer_questions', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'attend_class', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'change_society', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'determine_truth', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'examining_thing', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'get_contract', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'get_good_mark', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'go_to_school', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'improve_yourself', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learn', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learn_about_science', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learn_about_subject', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learn_about_world', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learn_language', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learn_new', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learning', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learning_about_subject', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learning_about_world', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'learning_language', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'memorize', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'pass_class', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'pass_course', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'pass_university_exams', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'passing_class', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'passing_course', 'direction': 1},
  {'rel': 'hasprerequisite',
   'tail': 'passing_university_exams',
   'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'reach_advantage', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'remember_phone_number', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'scholar', 'direction': 1},
  {'rel': 'hasprerequisite',
   'tail': 'see_idea_become_reality',
   'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'assignment', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'buy_textbook', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'concentrate', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'concentration', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'crack_books', 'direction': 0},
  {'rel': 'hasprerequisite',
   'tail': 'develop_good_study_habits',
   'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'eliminate_distractions', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'enroll_in_college', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'find_quiet_place', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'find_quiet_space', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'find_suitable_course', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'focus_on_what_reading', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'get_book', 'direction': 0},
  {'rel': 'hasprerequisite',
   'tail': 'get_rid_of_distractions',
   'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'go_someplace_quiet', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'go_to_library', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'have_book', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'open_book', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'open_book_s', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'open_text', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'open_textbooks', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'open_up_textbooks', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'procrastinate', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'read_book', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'read_books', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'reading_glasses', 'direction': 0},
  {'rel': 'hasprerequisite',
   'tail': 'repeat_fact_over_and_over',
   'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'scan_material', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'settle_down', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'turn_off_television', 'direction': 0},
  {'rel': 'hasprerequisite', 'tail': 'think', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'understand_better', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'understanding_better', 'direction': 1},
  {'rel': 'hasprerequisite', 'tail': 'write_term_paper', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'analyse', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'bone_up_on', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'buying', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'committing_to_memory', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'driving', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'emptying_bladder', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'examining_thing', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'getting_good_grade', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'have_examination', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'learn', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'learning_about_science', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'learning_about_subject', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'learning_language', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'pass_course', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'passing_class', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'passing_course', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'passing_university_exams', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'pleasing_parents', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'absorb_information', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'enlightenment', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'get_good_grades', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'know_subject_well', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'learn', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'learn_new', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'learn_things', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'learning', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'may_pass_test', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'might_get_smarter', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'read', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'read_book', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'read_over_notes', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'reading', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'reading_books', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'remember_what_already_know', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'turn_off_television', 'direction': 0},
  {'rel': 'hassubevent', 'tail': 'take_course', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'take_examination', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'take_final_exams', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'taking_course', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'taking_final_exams', 'direction': 1},
  {'rel': 'hassubevent', 'tail': 'wait_for', 'direction': 1},
  {'rel': 'isa', 'tail': 'aerobiology', 'direction': 1},
  {'rel': 'isa', 'tail': 'exercise_for_mind', 'direction': 0},
  {'rel': 'isa', 'tail': 'group_of_coordinated_research', 'direction': 0},
  {'rel': 'isa', 'tail': 'room_in_house', 'direction': 0},
  {'rel': 'isa', 'tail': "room_in_person's_house", 'direction': 0},
  {'rel': 'isa', 'tail': 'room', 'direction': 0},
  {'rel': 'isa', 'tail': 'room', 'direction': 0},
  {'rel': 'isa', 'tail': 'concentration', 'direction': 0},
  {'rel': 'isa', 'tail': 'learning', 'direction': 0},
  {'rel': 'isa', 'tail': 'musical_composition', 'direction': 0},
  {'rel': 'isa', 'tail': 'memorizer', 'direction': 0},
  {'rel': 'mannerof', 'tail': 'compare', 'direction': 1},
  {'rel': 'mannerof', 'tail': 'cram', 'direction': 1},
  {'rel': 'mannerof', 'tail': 'factor_out', 'direction': 1},
  {'rel': 'mannerof', 'tail': 'major', 'direction': 1},
  {'rel': 'mannerof', 'tail': 'memorize', 'direction': 1},
  {'rel': 'mannerof', 'tail': 'minor', 'direction': 1},
  {'rel': 'mannerof', 'tail': 'learn', 'direction': 0},
  {'rel': 'mannerof', 'tail': 'think', 'direction': 0},
  {'rel': 'mannerof', 'tail': 'chew_over', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'get_good_grade', 'direction': 1},
  {'rel': 'motivatedbygoal', 'tail': 'concentrate', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'do_well', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'educated', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'gain_knowledge', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'get_good_grades', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'good_grade', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'interested', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'know_about', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'knowledge_power', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'learn', 'direction': 0},
  {'rel': 'motivatedbygoal',
   'tail': 'learn_about_colonization_of_africa',
   'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'learn_things', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'make_parents_happy', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'pass_test', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'succeed_in_classes', 'direction': 0},
  {'rel': 'motivatedbygoal', 'tail': 'tired_of_being_dumb', 'direction': 0},
  {'rel': 'partof', 'tail': 'education', 'direction': 0},
  {'rel': 'partof', 'tail': 'house', 'direction': 0},
  {'rel': 'similarto', 'tail': 'boudoir', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'book', 'direction': 1},
  {'rel': 'usedfor', 'tail': 'population', 'direction': 1},
  {'rel': 'usedfor', 'tail': 'room_study', 'direction': 1},
  {'rel': 'usedfor', 'tail': 'being_student', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'doing_exam', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'gathering_information', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'isolated_study_activity', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'learn_things', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'learnig_for_subject', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'learning', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'pass_test', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'person_intensely_concentrating', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'place_to_study_subject', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'read', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'read_in_peace_and_quiet', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'reading', 'direction': 0},
  {'rel': 'usedfor', 'tail': 'surfing_net', 'direction': 1},
  {'rel': 'usedfor', 'tail': 'text', 'direction': 1},
  {'rel': 'usedfor', 'tail': 'university', 'direction': 1}],
 'atomic_infer': {'a reson to study',
  'a want to study something',
  'acknowledges that personx studies very hard',
  'acquire study materials.',
  'also to continue studies in correspondence',
  'analyze the study results',
  'appel for the higer study',
  'be a part of study',
  "can't study tonight.",
  'children to study',
  'childrens to study first class in school',
  'choose a school to study',
  'collect study materials',
  'complete studies',
  'concentrate on their studies now',
  'continue to study',
  'decide which career to study',
  'did not study',
  'difficult to study',
  'do feasibility study',
  'does a research on case studies',
  'enter the study',
  'find a place to study',
  'finished his studies',
  'for them to study',
  'forced to study',
  'forget to study',
  'gains study skills',
  'gather study materials',
  'get to study information that matters to them.',
  'gets invited to study',
  'gets stressed about the study',
  'go to study group',
  'goes to study',
  'has to study',
  'has to study catch up',
  'have to study',
  "he didn't study.",
  'he is well study',
  'he studies all night.',
  'he studies more on it.',
  'he studies the handbook.',
  'he studies the trade.',
  'higher studies',
  'him to come up in studies',
  'intend to study persony',
  'is asked to study',
  'is compelled to study',
  'join higher studies',
  'learned how to study properly',
  'learns how to study better',
  'like they should study',
  'material to study.',
  'meet a study partner',
  'need to study',
  'needs study.',
  'needs the quiet time to study',
  'not study',
  'not to be impressed by the present study',
  'open books and study',
  'pay for that school to study',
  'pay personx for participating in the study',
  'personx does not have time to study.',
  "personx doesn't need to study",
  'personx has to study nights',
  'personx puts study items away',
  'personx studies about the sport',
  'personx studies and tries to learn about rocks',
  'personx studies hard and then invites the neighbors over for ice cream',
  'personx studies harder for the next test',
  'personx studies less as a result of prior knowledge',
  'personx studies persony in depth.',
  'personx studies the event',
  'personx studies the instrument deeply',
  'personx study hard.',
  'persony to study harder.',
  'pick up their book and study',
  'police study circumstances of death',
  'prepare for the study',
  'proper study of the particular person',
  'read a textbook and study',
  'read information to study',
  'read studies',
  'realizes study is needed',
  'research the results to help advance a study',
  'resolve to study harder',
  'schedule time to devote to study.',
  'set up an area to study',
  'something to study',
  'starts to study harder',
  'studies',
  'studies a lot',
  'studies a new skill',
  'studies a subject',
  'studies all day and night',
  'studies at library',
  'studies carpentry',
  'studies hard',
  'studies harder',
  'studies in class.',
  'studies it',
  'studies martial arts',
  'studies more',
  'studies new topics to write about',
  'studies on line.',
  'studies patterns',

In [208]:
ConceptNet_keys = list(kb.ConceptNet.keys())

relation = {'causes':'xEffect','motivatedbygoal':'xIntent','hasprerequisite':'xNeed'}
#work: causes','motivatedbygoal','hasprerequisite'
#not work: 'usedfor',hassubevent','desires',
linking_word = set()
linking_noun_word = set()
remove_linking_words = ["run","bad",'drink','get','getting','give','know','look','seeing','stop',]
Next = 0

triplet_count = 0
ckb_newATOMIC = dict()
#while Next<10:
#for source in ConceptNet_keys:
    #source = [random.choice(ConceptNet_keys)]
    #source = ['attack']
    
    #print(source)
for src_word in ConceptNet_keys:
    if len(src_word) <= 2:
        #print(key, '\n', src_word,"\n")
        continue
    for kb_type, kb_values in kb.ConceptNet[src_word].items():
        if kb_type == 'conceptnet':
            #print(kb_type)
            for triple in kb_values:
                if triple['rel'] in relation and triple['direction']==1:
                    #print(triple['rel'])
                    for kb_type2, kb_values2 in kb.ConceptNet[triple['tail']].items():

                        #print(kb.ConceptNet[triple['tail']])
                        if kb_type2 == 'atomic_event' and kb_values2:
                            for key in kb_values2:
                                
                                if "n't" in key or 'never' in key or 'stop' in key or 'quit' in key:
                                    continue
                                if triple['tail'] in remove_linking_words:
                                    continue
                                if src_word == triple['tail']:
                                    continue
                                if src_word in key:
                                    #print(key, '\n', src_word,"\n")
                                    continue
                                
                                #if nltk.pos_tag(nltk.word_tokenize(triple['tail']))[0][1].startswith("NN") :
                                    #print(src_word,'->', triple['rel'],triple['direction'],'->',triple['tail'],'->',key )
                                #    linking_noun_word.add(triple['tail'])
                                #    continue
                                #if triple['tail'] == "think": 
                                #    print(src_word,'->', triple['rel'],triple['direction'],'->',triple['tail'],'->',key )
                                
                                if key not in ckb_newATOMIC: ckb_newATOMIC[key] = []
                                ckb_newATOMIC[key].append((triple['rel'], src_word))
                                triplet_count += 1
                                linking_word.add(triple['tail'])
                            #Next+=1

print(triplet_count)
print(triplet_count/877108)

175792
0.20042229691212485

In [73]:
import nltk

In [78]:
nltk.pos_tag(nltk.word_tokenize("car"))
#keywords = [word for (word, pos) in nltk.pos_tag(nltk.word_tokenize(text.lower())) if pos[:2] in ['NN', 'JJ', 'VB', "RB"] and word not in stopwords+persons ]

[('car', 'NN')]

In [66]:
240040/877108

0.2736721133543418

In [95]:
len(linking_word), len(linking_noun_word), triplet_count/877108

(87, 284, 0.08270475243641603)

In [84]:
linking_word

{'accomplish',
 'acting',
 'activity',
 'affair',
 'affect',
 'age',
 'air',
 'alarm',
 'alcohol',
 'ambulance',
 'anger',
 'anxiety',
 'apologize',
 'argue',
 'argument',
 'asking',
 'assault',
 'attack',
 'attractive',
 'awake',
 'awareness',
 'back',
 'bad',
 'bag',
 'baking',
 'baseball',
 'beer',
 'begin',
 'belief',
 'better',
 'bicycle',
 'bike',
 'birthday',
 'boil',
 'boring',
 'bounce',
 'bowl',
 'box',
 'break',
 'breathe',
 'breathing',
 'bribe',
 'broaden',
 'bubble',
 'building',
 'burn',
 'business',
 'buy',
 'buying',
 'california',
 'call',
 'calling',
 'camp',
 'cancer',
 'car',
 'cat',
 'celebrate',
 'celebrating',
 'change',
 'cheating',
 'cheer',
 'choke',
 'cigarette',
 'clap',
 'clean',
 'cleaning',
 'click',
 'climb',
 'climbing',
 'close',
 'coal',
 'coffee',
 'cold',
 'collapse',
 'communicate',
 'compete',
 'complain',
 'computer',
 'connect',
 'conversation',
 'convert',
 'cook',
 'cooking',
 'cool',
 'cough',
 'coughing',
 'crack',
 'crash',
 'crisis',
 'crutch',
 'cry',
 'cut',
 'damage',
 'dance',
 'dancing',
 'darken',
 'darkness',
 'data',
 'dating',
 'death',
 'decide',
 'depression',
 'desire',
 'destroy',
 'develop',
 'die',
 'difference',
 'direct',
 'donate',
 'dream',
 'drench',
 'drink',
 'drinking',
 'drive',
 'driving',
 'drug',
 'dry',
 'duck',
 'dying',
 'earth',
 'eat',
 'eating',
 'effect',
 'email',
 'empty',
 'encourage',
 'end',
 'engine',
 'entertained',
 'even',
 'exercise',
 'exercising',
 'explosion',
 'fall',
 'falling',
 'fear',
 'fell',
 'fence',
 'fever',
 'fiddle',
 'fill',
 'fire',
 'fish',
 'fishing',
 'fit',
 'flirting',
 'floss',
 'flow',
 'flush',
 'fly',
 'flying',
 'focus',
 'follow',
 'forgive',
 'free',
 'freeze',
 'freezing',
 'friendship',
 'frighten',
 'fruit',
 'funeral',
 'gamble',
 'gambling',
 'get',
 'getting',
 'ghost',
 'give',
 'god',
 'graduate',
 'grass',
 'grin',
 'grow',
 'growl',
 'guitar',
 'gymnastics',
 'hail',
 'hammer',
 'hang',
 'happy',
 'harden',
 'hate',
 'healthy',
 'hear',
 'hearing',
 'heart',
 'heat',
 'help',
 'helping',
 'hike',
 'hiking',
 'hit',
 'homework',
 'host',
 'hug',
 'hunger',
 'hunting',
 'hurt',
 'ignorance',
 'infection',
 'information',
 'injury',
 'inquiry',
 'instrument',
 'insult',
 'job',
 'jogging',
 'join',
 'joke',
 'judge',
 'jump',
 'jumping',
 'kick',
 'kill',
 'killing',
 'kind',
 'kiss',
 'kissing',
 'knit',
 'knitting',
 'know',
 'knowledge',
 'land',
 'laugh',
 'laughing',
 'lawn',
 'lay',
 'leak',
 'learn',
 'learning',
 'leave',
 'lie',
 'life',
 'lift',
 'lighten',
 'lightning',
 'listen',
 'listening',
 'live',
 'living',
 'lock',
 'look',
 'loosen',
 'losing',
 'love',
 'loving',
 'lower',
 'lying',
 'marble',
 'march',
 'marriage',
 'marry',
 'match',
 'medication',
 'melt',
 'memorize',
 'millionaire',
 'miserable',
 'misunderstanding',
 'money',
 'move',
 'murder',
 'nice',
 'noise',
 'open',
 'organization',
 'pack',
 'pain',
 'paint',
 'painting',
 'panic',
 'pass',
 'pee',
 'perform',
 'play',
 'playing',
 'plunge',
 'poison',
 'poisoning',
 'poop',
 'pour',
 'practice',
 'pray',
 'pressure',
 'pretend',
 'produce',
 'professional',
 'program',
 'programming',
 'project',
 'pulse',
 'punch',
 'punish',
 'puppy',
 'purchase',
 'rain',
 'raise',
 'read',
 'reading',
 'rear',
 'recall',
 'relax',
 'religion',
 'remember',
 'remind',
 'reproduce',
 'resign',
 'rest',
 'restaurant',
 'retire',
 'rich',
 'ring',
 'running',
 'rush',
 'sailing',
 'scared',
 'scratch',
 'season',
 'seat',
 'see',
 'seeing',
 'sell',
 'sentence',
 'separate',
 'sew',
 'shave',
 'shine',
 'shiver',
 'shop',
 'shopping',
 'shove',
 'show',
 'shower',
 'sin',
 'sing',
 'singing',
 'sink',
 'skate',
 'skateboard',
 'ski',
 'skiing',
 'skip',
 'sleep',
 'sleeping',
 'slip',
 'smile',
 'smoke',
 'smoking',
 'sneeze',
 'sneezing',
 'snow',
 'soften',
 'sound',
 'speak',
 'speed',
 'speeding',
 'spit',
 'sport',
 'stab',
 'stand',
 'start',
 'starve',
 'steal',
 'steer',
 'stop',
 'strengthen',
 'stress',
 'struggle',
 'study',
 'studying',
 'subject',
 'succeed',
 'success',
 'successful',
 'sue',
 'sugar',
 'sun',
 'sunburn',
 'surf',
 'surfing',
 'surprise',
 'survival',
 'swallow',
 'swell',
 'swim',
 'swimming',
 'switch',
 'system',
 'talk',
 'talking',
 'taller',
 'teach',
 'teacher',
 'teaching',
 'thank',
 'thin',
 'think',
 'thinking',
 'thirst',
 'tickle',
 'tide',
 'tire',
 'travel',
 'traveling',
 'trip',
 'tv',
 'typing',
 'understand',
 'unemployment',
 'use',
 'violence',
 'vote',
 'voting',
 'waiting',
 'walk',
 'walking',
 'war',
 'waste',
 'wedding',
 'widen',
 'wind',
 'wing',
 'winning',
 'work',
 'working',
 'worry',
 'wrestle',
 'wrestling',
 'write',
 'writing',
 'yell',
 'yelling'}

## Fomatting New Triplets

In [118]:
len(ckb_newATOMIC)

7301

## build new train file

In [209]:
atomic_rels = ["oEffect","oReact","oWant","xAttr","xEffect","xIntent","xNeed","xReact","xWant"]
with open('atomic_train_ckb.csv','w',encoding="utf-8") as fout:
    fout.write("event,oEffect,oReact,oWant,xAttr,xEffect,xIntent,xNeed,xReact,xWant,prefix,split"+"\n")#,prefix,split
    
    for key, tails in ckb_newATOMIC.items():
        if "," in key: continue
            
        fout.write(key+",")
        merged = {ato_rel:set() for ato_rel in relation.values() }
        for rel, tail in tails:
            merged[relation[rel]].add('"'+tail+'"')
        for atomic_rel in atomic_rels:
            if atomic_rel in merged and merged[atomic_rel]:
                fout.write('"[')
                for idx, item in enumerate(merged[atomic_rel]):
                    fout.write('"'+item.replace("_"," ")+'"')
                    if idx < len(merged[atomic_rel])-1 : 
                        fout.write(", ")
                fout.write(']"')
            else:
                fout.write("[]")
                
            if atomic_rel == 'xWant':
                fout.write(",[],[]\n")
            else:
                fout.write(",")
        #fout.write()

In [224]:
import pandas
import json
categories = []
categories += ["oEffect"]
categories += ["oReact"]
categories += ["oWant"]
categories += ["xAttr"]
categories += ["xEffect"]
categories += ["xIntent"]
categories += ["xNeed"]
categories += ["xReact"]
categories += ["xWant"]
def zipped_flatten(outer):
    return [(key, fill, el) for key, fill, inner in outer for el in inner]

In [241]:
file_name = "/mnt/cephfs2/nlp/gengyu.wang/comet-commonsense/data/atomic/v4_atomic_dev.csv"
data = {"total": []}
df = pandas.read_csv(file_name, index_col=0)
df.iloc[:, :9] = df.iloc[:, :9].apply(
    lambda col: col.apply(json.loads))
for cat in categories:
    attr = df[cat]
    data["total"] += zipped_flatten(zip(
        attr.index, ["<{}>".format(cat)] * len(attr), attr.values))

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22620 entries, PersonX plays a ___ in the war to PersonX is playing with PersonY's friends
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   oEffect  22620 non-null  object
 1   oReact   22620 non-null  object
 2   oWant    22620 non-null  object
 3   xAttr    22620 non-null  object
 4   xEffect  22620 non-null  object
 5   xIntent  22620 non-null  object
 6   xNeed    22620 non-null  object
 7   xReact   22620 non-null  object
 8   xWant    22620 non-null  object
 9   prefix   22620 non-null  object
 10  split    22620 non-null  object
dtypes: object(11)
memory usage: 2.1+ MB

In [239]:
file_name = "/mnt/cephfs2/nlp/gengyu.wang/comet-commonsense/data/atomic/v4_atomic_trn.csv"
file_name = "/mnt/cephfs2/nlp/gengyu.wang/connected-KG-for-QA/atomic_train_ckb.csv"

data_our = {"total": []}
df_our = pandas.read_csv(file_name, index_col=0)
df_our.iloc[:, :9] = df_our.iloc[:, :9].apply(
    lambda col: col.apply(json.loads))
for cat in categories:
    attr = df_our[cat]
    data_our["total"] += zipped_flatten(zip(
        attr.index, ["<{}>".format(cat)] * len(attr), attr.values))

df_our.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7230 entries, PersonX has a drinking problem to PersonX switches back
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   oEffect  7230 non-null   object
 1   oReact   7230 non-null   object
 2   oWant    7230 non-null   object
 3   xAttr    7230 non-null   object
 4   xEffect  7230 non-null   object
 5   xIntent  7230 non-null   object
 6   xNeed    7230 non-null   object
 7   xReact   7230 non-null   object
 8   xWant    7230 non-null   object
 9   prefix   7230 non-null   object
 10  split    7230 non-null   object
dtypes: object(11)
memory usage: 677.8+ KB

In [221]:
df.iloc[3,4]

['PersonX is injured from war', 'PersonX is considered a hero']

In [238]:
df_our.iloc[0]

oEffect                                                   []
oReact                                                    []
oWant                                                     []
xAttr                                                     []
xEffect    [quenching thirst, need to urinate, hydrating ...
xIntent                                                   []
xNeed      [thirst, liquer, glass, from which to drink, s...
xReact                                                    []
xWant                                                     []
prefix                                                    []
split                                                     []
Name: PersonX has a drinking problem, dtype: object

In [242]:
data['total'][0:10]

[('PersonX plays a ___ in the war', '<oEffect>', 'none'),
 ('PersonX plays a ___ in the war', '<oEffect>', 'none'),
 ('PersonX plays a ___ in the war', '<oEffect>', 'Helped'),
 ('PersonX plays a ___ in the war', '<oEffect>', 'Won'),
 ('PersonX plays a ___ in the economy', '<oEffect>', 'none'),
 ('PersonX plays a ___ in the economy', '<oEffect>', 'none'),
 ('PersonX plays a ___ in the economy', '<oEffect>', 'none'),
 ('PersonX focuses ___ on issues', '<oEffect>', 'none'),
 ("PersonX hardens pharaoh 's ___",
  '<oEffect>',
  'The pharaoh screams in extraordinary pain'),
 ("PersonX hardens pharaoh 's ___", '<oEffect>', 'The pharaoh dies')]

In [240]:
data_our['total'][0:10]

[('PersonX has a drinking problem', '<xEffect>', 'quenching thirst'),
 ('PersonX has a drinking problem', '<xEffect>', 'need to urinate'),
 ('PersonX has a drinking problem', '<xEffect>', 'hydrating body'),
 ('PersonX has a drinking problem', '<xEffect>', 'vomiting'),
 ('PersonX has a drinking problem', '<xEffect>', 'headaches'),
 ('PersonX has a drinking problem', '<xEffect>', 'hydration'),
 ('PersonX has a drinking problem', '<xEffect>', 'hangover'),
 ('PersonX has a drinking problem', '<xEffect>', 'loss of control'),
 ('PersonX has a drinking problem', '<xEffect>', 'getting totally drunk'),
 ('PersonX has a drinking problem', '<xEffect>', 'getting drunk')]

### insert to orginal atomic

In [137]:
import csv
import json

In [336]:
atomic_rels = ["oEffect","oReact","oWant","xAttr","xEffect","xIntent","xNeed","xReact","xWant"]

processed_events = set()
csv_reader = pandas.read_csv("../comet-commonsense/data/atomic/v4_atomic_trn.csv.original", index_col=0)
for row in csv_reader.iterrows():
    event = row[0]
    infers = row[1]
    #print(row)
    if event in ckb_newATOMIC and event not in processed_events:
        processed_events.add(event)
        merged = {ato_rel:set() for ato_rel in relation.values() }
        for rel, tail in ckb_newATOMIC[event]:
            merged[relation[rel]].add(tail.replace("_"," "))

        for rel_id, atomic_rel in enumerate(atomic_rels):
            if atomic_rel in merged and merged[atomic_rel]:
                if infers[rel_id+1]=="[]":
                    orig_tails = set()
                else:
                    #orig_tails = set(infers[rel_id+1].strip('][').split(', '))
                    orig_tails = set(json.loads(infers[rel_id+1]))
                orig_tails.update(merged[atomic_rel])
                new_tails = list(orig_tails)
                write_string = json.dumps(new_tails)
                #print(row)

                row[1][rel_id+1] = write_string
                #print(row[1][rel_id+1])
                #print(row)
        #break

csv_reader.to_csv("v4_atomic_trn.csv.py", index=True)

In [321]:
for row in csv_reader.iterrows():
    print(type(row[1]))
    print(type(row[1][1]))
    break

<class 'pandas.core.series.Series'>
<class 'str'>

In [ ]:
df = pandas.read_csv("v4_atomic_trn.csv.py", index_col=0)
#df.iloc[:, :9] = df.iloc[:, :9].apply(
#    lambda col: col.apply(json.loads))

In [330]:
for row json.loads(df.iloc[0, :9][0])

[]

### Find paths for missed QA pairs

In [137]:
import os

In [146]:
file_list = ["trn_s11","dev","tst","trn_s0","trn_s1","trn_s2","trn_s3","trn_s4","trn_s5","trn_s6","trn_s7","trn_s8","trn_s9","trn_s10"]
data_dir = "SocialIQa/"

for filename in file_list:
    all_keywords = pickle.load(open(os.path.join(data_dir, "socialIQa_v1.4_"+filename.split('_')[0]+"_keywords.pickle"), 'rb'))
    
    all_paths = pickle.load(open(os.path.join(data_dir, "socialIQa_v1.4_"+filename+"_knowledgePath.pickle"), 'rb'))

    for index, qa_pair in enumerate(all_paths):
        if filename.startswith("trn"):
            dict_index = int(filename.split("s")[1]) * 3000 + index + 1
        else: dict_index = index + 1
        for cq_word in all_keywords[dict_index]["cq_word"]:
            if "." in cq_word:

            for a_word in all_keywords[dict_index]["a_word"]:
                paths = kb.search_path_byEntity(cq_word, a_word, 3)
                if paths:
                    all_paths[index].append(paths)
    for idx, qa_pair in enumerate(all_paths):
        if not qa_pair:
            print("missed:",filename, idx)
    
    pickle.dump(all_paths, open(os.path.join(data_dir, "socialIQa_v1.4_"+filename+"_knowledgePath_all.pickle"), 'wb'))
    print(filename, "done")

dev done
tst done
trn_s0 done
trn_s1 done
trn_s2 done
trn_s3 done
trn_s4 done
trn_s5 done
trn_s6 done
trn_s7 done
trn_s8 done
missed: trn_s9 801
trn_s9 done
trn_s10 done

### Fix error:  'tree.how' in keywords

In [159]:
import multiprocessing

In [161]:
file_list = ["dev","tst","trn_s0","trn_s2","trn_s5","trn_s6","trn_s8","trn_s9",]

#"trn_s11", "trn_s3", "trn_s1","trn_s7","trn_s10" "trn_s4",
def loop_file(filename):
    #kb_sub = Connected_KB()
    data_dir = "SocialIQa/"
    #for filename in file_list:
    all_keywords = pickle.load(open(os.path.join(data_dir, "socialIQa_v1.4_"+filename.split('_')[0]+"_keywords.pickle"), 'rb'))
    
    all_paths = pickle.load(open(os.path.join(data_dir, "socialIQa_v1.4_"+filename+"_knowledgePath_all.pickle"), 'rb'))

    for index, qa_pair in enumerate(all_paths):
        if filename.startswith("trn"):
            dict_index = int(filename.split("s")[1]) * 3000 + index + 1
        else: dict_index = index + 1
        
        remove_list = []
        for cq_word in all_keywords[dict_index]["cq_word"]:
            if "." in cq_word:
                remove_list.append(cq_word)
                new_keywords = kb_sub.get_keywords_from_text(cq_word.replace('.',' '))
                #print("remove:",filename, index, cq_word,"->", new_keywords )
                
                for kw in new_keywords:
                    for a_word in all_keywords[dict_index]["a_word"]:
                        paths = kb_sub.search_path_byEntity(kw, a_word, 3)
                        if paths:
                            all_paths[index].append(paths)
        
        for remove_word in remove_list:
            all_keywords[dict_index]["cq_word"].remove(remove_word)
    for idx, qa_pair in enumerate(all_paths):
        if not qa_pair:
            print("missed:",filename, idx)
    
    pickle.dump(all_paths, open(os.path.join(data_dir, "socialIQa_v1.4_"+filename+"_knowledgePath_all_fix.pickle"), 'wb'))
    pickle.dump(all_keywords, open(os.path.join(data_dir, "socialIQa_v1.4_"+filename.split('_')[0]+"_keywords.pickle"), 'wb'))
    
    return filename
    #print(filename, "done")
    
cores = multiprocessing.cpu_count()
pool = multiprocessing.Pool(processes=cores)
print("Runing on", cores, "CPUs.")
for filename in pool.map(loop_file, file_list):
    print(filename, "done")

Runing on 48 CPUs.

Exception in thread Thread-25:
Traceback (most recent call last):
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/pool.py", line 405, in _handle_workers
    pool._maintain_pool()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/pool.py", line 246, in _maintain_pool
    self._repopulate_pool()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

Process ForkPoolWorker-61:
Process ForkPoolWorker-90:
Process ForkPoolWorker-80:
Process ForkPoolWorker-69:
Process ForkPoolWorker-91:
Process ForkPoolWorker-73:
Process ForkPoolWorker-81:
Process ForkPoolWorker-67:
Process ForkPoolWorker-68:
Process ForkPoolWorker-84:
Process ForkPoolWorker-58:
Process ForkPoolWorker-74:
Process ForkPoolWorker-93:
Process ForkPoolWorker-54:
Process ForkPoolWorker-77:
Process ForkPoolWorker-55:
Process ForkPoolWorker-72:
Process ForkPoolWorker-89:
Process ForkPoolWorker-62:
Process ForkPoolWorker-83:
Process ForkPoolWorker-65:
Process ForkPoolWorker-78:
Process ForkPoolWorker-71:
Process ForkPoolWorker-66:
Process ForkPoolWorker-94:
Process ForkPoolWorker-82:
Process ForkPoolWorker-52:
Process ForkPoolWorker-70:
Process ForkPoolWorker-76:
Process ForkPoolWorker-85:
Process ForkPoolWorker-75:
Process ForkPoolWorker-92:
Process ForkPoolWorker-64:
Process ForkPoolWorker-79:
Process ForkPoolWorker-88:
Process ForkPoolWorker-87:
Process ForkPoolWorker-86:
Process ForkPoolWorker-96:
Process ForkPoolWorker-95:
Process ForkPoolWorker-63:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/queues.py", line 334, in get
    with self._rlock:
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()

  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/mnt/cephfs2/nlp/gengyu.wang/miniconda3/envs/trans/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()

In [152]:
temp_list = []
for cq_word in all_keywords[27802]["cq_word"]:
    for a_word in all_keywords[27802]["a_word"]:
        paths = kb.search_path_byEntity(cq_word, a_word, 3)
        temp_list.append(paths)
all_keywords[27802], temp_list

({'cq_word': {'describe',
   'flower.how',
   'sasha',
   'sleeve',
   'smelling',
   'sneezed'},
  'a_word': {'allergic', 'pollin', 'stuffy', 'unkind'}},
 [[],
  None,
  None,
  [],
  [],
  None,
  None,
  [],
  None,
  None,
  None,
  None,
  [],
  None,
  None,
  [],
  [],
  None,
  None,
  [],
  [],
  None,
  None,
  []])

In [144]:
rel = data[0][3]
#kb.search_path_byEntity("ocean","castle",3)
print(len(rel))
for r in rel:
    for d in r:
        print(d['rel_w_parent'] if d['rel_w_parent'] else "->", "【", d["kb_type"].upper(), ":", d['key'], "】")
    print(" ")

540
-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
xReact 【 ATOMIC_EVENT : PersonX does n't know what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonX's hat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY alive 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's bread 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's candy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's homework 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's lunch 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonY's meal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's sandwich 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ for weeks 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
xReact 【 ATOMIC_EVENT : PersonX eats all of PersonY's food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
oReact 【 ATOMIC_EVENT : PersonX eats and ___ to drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : angry 】
xAttr 【 ATOMIC_EVENT : PersonX would n't eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonX's bread 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonX's meal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY dinner 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's lunch 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's meal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonY's meal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
oReact 【 ATOMIC_INFER : upset 】
xReact 【 ATOMIC_EVENT : PersonX would n't eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xAttr 【 ATOMIC_INFER : unsatisfied 】
xReact 【 ATOMIC_EVENT : PersonX tries to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xAttr 【 ATOMIC_INFER : decisive 】
xAttr 【 ATOMIC_EVENT : PersonX decides what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xAttr 【 ATOMIC_INFER : decisive 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ everyday 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xAttr 【 ATOMIC_INFER : decisive 】
xAttr 【 ATOMIC_EVENT : PersonX eats cereal instead 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xAttr 【 ATOMIC_INFER : decisive 】
xAttr 【 ATOMIC_EVENT : PersonX wants to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xIntent 【 ATOMIC_INFER : to move on 】
xWant 【 ATOMIC_EVENT : PersonX eats crow 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : relieved 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ instead 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : relieved 】
xReact 【 ATOMIC_EVENT : PersonX refuses to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonX's bread 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonX's meal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY dinner 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's lunch 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's meal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonY's meal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit 】
xReact 【 ATOMIC_INFER : upset 】
xReact 【 ATOMIC_EVENT : PersonX would n't eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : bored 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ anyway 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : bored 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every morning 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : bored 】
xAttr 【 ATOMIC_EVENT : PersonX eats junk food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : bored 】
xAttr 【 ATOMIC_EVENT : PersonX eats my food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : bored 】
xAttr 【 ATOMIC_EVENT : PersonX eats snacks 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : bored 】
xAttr 【 ATOMIC_EVENT : PersonX eats some food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX decides to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : determined 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ for weeks 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats chicken 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats crackers 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats more healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : adventurous 】
xAttr 【 ATOMIC_EVENT : PersonX begins to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : adventurous 】
xAttr 【 ATOMIC_EVENT : PersonX eats crow 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : adventurous 】
xAttr 【 ATOMIC_EVENT : PersonX eats fried chicken 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : adventurous 】
xAttr 【 ATOMIC_EVENT : PersonX eats it anyway 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : adventurous 】
xReact 【 ATOMIC_EVENT : PersonX eats one 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : adventurous 】
xAttr 【 ATOMIC_EVENT : PersonX eats something 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xAttr 【 ATOMIC_INFER : adventurous 】
xAttr 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : nervous 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ very quickly 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : nervous 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ with PersonY's family 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : nervous 】
xAttr 【 ATOMIC_EVENT : PersonX eats nothing 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : nervous 】
xAttr 【 ATOMIC_EVENT : PersonX tries to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xWant 【 ATOMIC_EVENT : PersonX eats , drank 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonX's candy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonX's cookies 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonX's cookies 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonX's own dog food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonY breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonY's flesh 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonY's lunch 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ all the time 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ alone 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oWant 【 ATOMIC_EVENT : PersonX eats ___ anyway 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ ever 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every morning 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ for days 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ for dinner 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ happily 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ in one 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ like the ox 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ outside 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ quickly 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ that night 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ together 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ together 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ with PersonX's family 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ with PersonX's family 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ with PersonX's family 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ with PersonY's family 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ with PersonY's family 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats a slice 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats an apple 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats and ___ to drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats another ___ 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats at a fancy restaurant 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX eats at a nice restaurant 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats at a nice restaurant 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats at home 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats bread 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats buffet 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats cake 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats chicken wings 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats crow 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats delicious food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats delicious food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats enough 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats for dinner 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats fruit 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats fruit 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats grass 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats hamburgers 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats ice cream 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats lunch with PersonY 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats lunch with PersonY 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats more healthy food 】


-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats popcorn 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats potato chips 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats potato chips 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats quickly 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats snacks 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats so much 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats some ice cream 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats some ice cream 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats spaghetti 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats steak 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats sushi 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats sweets 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats the cake 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats the cake 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats the cookies 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats the ice cream 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats the soup 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats together 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats together 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xEffect 【 ATOMIC_EVENT : PersonX eats too many sweets 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX eats with PersonX's friends 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats with PersonX's friends 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX eats with PersonY's friends 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xAttr 【 ATOMIC_EVENT : PersonX eats with PersonY's friends 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX eats with PersonY's friends 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX gets ___ to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX likes to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX loves to eat ice cream 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX starts to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX takes PersonY out to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX takes PersonY out to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
oReact 【 ATOMIC_EVENT : PersonX takes ___ out to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX decides to quit PersonX's job 】
xReact 【 ATOMIC_INFER : happy 】
xReact 【 ATOMIC_EVENT : PersonX wants to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX decides to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ for weeks 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats chicken 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats crackers 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats more healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : successful 】
xReact 【 ATOMIC_EVENT : PersonX eats at a nice restaurant 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ every night 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats or drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX never eat ___ 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : active 】
xAttr 【 ATOMIC_EVENT : PersonX eats pasta 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : active 】
xAttr 【 ATOMIC_EVENT : PersonX eats the soup 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : aware 】
xAttr 【 ATOMIC_EVENT : PersonX eats an apple 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : aware 】
xAttr 【 ATOMIC_EVENT : PersonX eats chicken 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : aware 】
xAttr 【 ATOMIC_EVENT : PersonX eats more healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : disciplined 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy foods 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : disciplined 】
xAttr 【 ATOMIC_EVENT : PersonX eats more healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xAttr 【 ATOMIC_INFER : disciplined 】
xAttr 【 ATOMIC_EVENT : PersonX never eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xEffect 【 ATOMIC_INFER : saves money 】
xEffect 【 ATOMIC_EVENT : PersonX eats at home 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xEffect 【 ATOMIC_INFER : saves money 】
xEffect 【 ATOMIC_EVENT : PersonX eats fast food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthier 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ anymore 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthier 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ everyday 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthier 】
xIntent 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthier 】
xNeed 【 ATOMIC_EVENT : PersonX eats healthy foods 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthier 】
xIntent 【 ATOMIC_EVENT : PersonX eats less 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthier 】
xIntent 【 ATOMIC_EVENT : PersonX eats spinach 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthier 】
xWant 【 ATOMIC_EVENT : PersonX never eat ___ again 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonX's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonY's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ all the time 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ every morning 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ every single day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ for a week 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats ___ for a week 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ for breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats a banana 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats enough 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats every ___ 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats fruit 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats it every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats it every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats more vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats more vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats something healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats well 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX knows what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to save money 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonY's dinner 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to save money 】

xWant 【 ATOMIC_EVENT : PersonX eats ___ at home 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xIntent 【 ATOMIC_INFER : to save money 】
xWant 【 ATOMIC_EVENT : PersonX eats less 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xReact 【 ATOMIC_INFER : powerful 】
oReact 【 ATOMIC_EVENT : PersonX eats out of PersonY's hand 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xReact 【 ATOMIC_INFER : powerful 】
xReact 【 ATOMIC_EVENT : PersonX eats some food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xReact 【 ATOMIC_INFER : accomplished 】
oReact 【 ATOMIC_EVENT : PersonX eats PersonY's breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xReact 【 ATOMIC_INFER : accomplished 】
xReact 【 ATOMIC_EVENT : PersonX eats more healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xReact 【 ATOMIC_INFER : accomplished 】
xReact 【 ATOMIC_EVENT : PersonX eats more vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX is trying to quit smoking 】
xReact 【 ATOMIC_INFER : accomplished 】
xAttr 【 ATOMIC_EVENT : PersonX has PersonX's cake and eat it too 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xAttr 【 ATOMIC_INFER : confident 】
xAttr 【 ATOMIC_EVENT : PersonX begins to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xAttr 【 ATOMIC_INFER : confident 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ quickly 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xAttr 【 ATOMIC_INFER : independant 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ for days 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xAttr 【 ATOMIC_INFER : dedicated 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ for days 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xAttr 【 ATOMIC_INFER : dedicated 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xAttr 【 ATOMIC_INFER : dedicated 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xAttr 【 ATOMIC_INFER : dedicated 】
xAttr 【 ATOMIC_EVENT : PersonX tries to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xReact 【 ATOMIC_INFER : independent 】
xAttr 【 ATOMIC_EVENT : PersonX eats and ___ to drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xReact 【 ATOMIC_INFER : independent 】
xAttr 【 ATOMIC_EVENT : PersonX eats cheese 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit on PersonX's own 】
xReact 【 ATOMIC_INFER : independent 】
xAttr 【 ATOMIC_EVENT : PersonX eats or drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : successful 】
xReact 【 ATOMIC_EVENT : PersonX eats at a nice restaurant 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ every night 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats or drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX never eat ___ 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonX's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonX's wheaties 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonY's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonY's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonY's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every night 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ everyday 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ for a week 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ for breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats a banana 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats a lot of food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats an apple 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats an apple 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats chicken 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats fish 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats for lunch 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats fruit 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy foods 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats healthy foods 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats more vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats or drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats red meat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats rice 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats seafood 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats something healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats spinach 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats spinach 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats well 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats well 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX knows what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xAttr 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xEffect 【 ATOMIC_INFER : get hungry 】
xNeed 【 ATOMIC_EVENT : PersonX decides what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xEffect 【 ATOMIC_INFER : get hungry 】
xNeed 【 ATOMIC_EVENT : PersonX eats ___ together 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xEffect 【 ATOMIC_INFER : gets hungry 】
xNeed 【 ATOMIC_EVENT : PersonX decides to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xEffect 【 ATOMIC_INFER : gets hungry 】
oEffect 【 ATOMIC_EVENT : PersonX eats PersonY breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xEffect 【 ATOMIC_INFER : gets hungry 】
oEffect 【 ATOMIC_EVENT : PersonX eats PersonY's dinner 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xEffect 【 ATOMIC_INFER : gets hungry 】
oEffect 【 ATOMIC_EVENT : PersonX eats PersonY's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xEffect 【 ATOMIC_INFER : gets hungry 】
xEffect 【 ATOMIC_EVENT : PersonX eats nothing 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xEffect 【 ATOMIC_INFER : gets hungry 】
xEffect 【 ATOMIC_EVENT : PersonX wants to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonX's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonY's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ all the time 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ every morning 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ every single day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ for a week 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats ___ for a week 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ for breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats a banana 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats enough 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats every ___ 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats fruit 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats it every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats it every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats more vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats more vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xWant 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats something healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xIntent 【 ATOMIC_INFER : to be healthy 】

xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonY's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonY's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every night 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ everyday 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ for a week 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ for breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats a banana 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats a lot of food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats an apple 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats an apple 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats chicken 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats fish 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats for lunch 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats fruit 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy foods 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats healthy foods 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats more vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats or drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats red meat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats rice 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats seafood 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats something healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats spinach 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats spinach 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats well 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats well 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX knows what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xWant 【 ATOMIC_INFER : to exercise 】
xWant 【 ATOMIC_EVENT : PersonX eats cookies 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xWant 【 ATOMIC_INFER : to exercise 】
xWant 【 ATOMIC_EVENT : PersonX eats for two 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xWant 【 ATOMIC_INFER : to exercise 】
xWant 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xWant 【 ATOMIC_INFER : to exercise 】
xWant 【 ATOMIC_EVENT : PersonX eats healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xWant 【 ATOMIC_INFER : to exercise 】
xWant 【 ATOMIC_EVENT : PersonX eats less 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xWant 【 ATOMIC_INFER : to exercise 】
xWant 【 ATOMIC_EVENT : PersonX eats too many sweets 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX tries to quit smoking 】
xWant 【 ATOMIC_INFER : to eat healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : fed up 】
xReact 【 ATOMIC_EVENT : PersonX eats at a fancy restaurant 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : fed up 】
xReact 【 ATOMIC_EVENT : PersonX eats it quickly 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : frustrated 】
xReact 【 ATOMIC_EVENT : PersonX does n't know what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : frustrated 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ instead 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : mature 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ every night 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats or drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xAttr 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : responsible 】
xReact 【 ATOMIC_EVENT : PersonX never eat ___ 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : tired 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonX's own dog food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : tired 】
xAttr 【 ATOMIC_EVENT : PersonX eats a banana 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : tired 】
oReact 【 ATOMIC_EVENT : PersonX eats at a restaurant 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : tired 】
xReact 【 ATOMIC_EVENT : PersonX eats fast food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : tired 】
oReact 【 ATOMIC_EVENT : PersonX eats italian food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xAttr 【 ATOMIC_INFER : tired 】
xAttr 【 ATOMIC_EVENT : PersonX starts to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xReact 【 ATOMIC_INFER : relieved 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ instead 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xReact 【 ATOMIC_INFER : relieved 】
xReact 【 ATOMIC_EVENT : PersonX refuses to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xWant 【 ATOMIC_INFER : to try something new 】
xIntent 【 ATOMIC_EVENT : PersonX eats grass 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xWant 【 ATOMIC_INFER : to try something new 】
xIntent 【 ATOMIC_EVENT : PersonX eats one 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit 】
xWant 【 ATOMIC_INFER : to try something new 】
xWant 【 ATOMIC_EVENT : PersonX eats sushi 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX decides to eat it 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ for weeks 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats chicken 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats crackers 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : determined 】
xAttr 【 ATOMIC_EVENT : PersonX eats more healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : frustrated 】
xReact 【 ATOMIC_EVENT : PersonX does n't know what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : frustrated 】
oReact 【 ATOMIC_EVENT : PersonX eats ___ instead 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : motivated 】
xAttr 【 ATOMIC_EVENT : PersonX eats a banana 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : motivated 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : motivated 】
xAttr 【 ATOMIC_EVENT : PersonX eats the steak 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : motivated 】
xAttr 【 ATOMIC_EVENT : PersonX wants to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : health conscious 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : health conscious 】
xAttr 【 ATOMIC_EVENT : PersonX eats more healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : health conscious 】
xAttr 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : health conscious 】
xAttr 【 ATOMIC_EVENT : PersonX eats spinach 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xAttr 【 ATOMIC_INFER : health conscious 】
xAttr 【 ATOMIC_EVENT : PersonX eats the sandwich 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : clean 】
xAttr 【 ATOMIC_EVENT : PersonX is ready to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : contented with himself 】
xReact 【 ATOMIC_EVENT : PersonX decides what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : contented with himself 】
xReact 【 ATOMIC_EVENT : PersonX eats fruit 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonX's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonX's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonX's wheaties 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats PersonY's plants 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats PersonY's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats PersonY's vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xIntent 【 ATOMIC_EVENT : PersonX eats ___ every day 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ every night 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ everyday 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats ___ for a week 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats ___ for breakfast 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats a banana 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats a lot of food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats an apple 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats an apple 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats better 】

-> 【 CONCEPTNET : quit 】

-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats good food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats healthier 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy foods 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats healthy foods 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats healthy things 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats more vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats oatmeal 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats or drink 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats red meat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats rice 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats right 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats seafood 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats something healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats spinach 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats spinach 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats the vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats tofu 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats vegetables 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX eats well 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX eats well 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX knows what to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xAttr 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_EVENT : PersonX wants to quit smoking 】
xReact 【 ATOMIC_INFER : healthy 】
xReact 【 ATOMIC_EVENT : PersonX loves to eat apples 】

-> 【 CONCEPTNET : quit 】
hasprerequisite 【 CONCEPTNET : smoke 】
-> 【 ATOMIC_EVENT : PersonX smokes PersonX's pipe 】
xWant 【 ATOMIC_INFER : to eat 】

-> 【 CONCEPTNET : quit 】
hasprerequisite 【 CONCEPTNET : smoke 】
-> 【 ATOMIC_EVENT : PersonX starts to smoke 】
xWant 【 ATOMIC_INFER : to eat a mint 】

-> 【 CONCEPTNET : quit 】
hasprerequisite 【 CONCEPTNET : smoke 】
causes 【 CONCEPTNET : cooking 】
hassubevent 【 CONCEPTNET : eat 】

-> 【 CONCEPTNET : quit 】
hasprerequisite 【 CONCEPTNET : smoke 】
hasfirstsubevent 【 CONCEPTNET : light_cigarette 】
haslastsubevent 【 CONCEPTNET : eat 】

-> 【 CONCEPTNET : quit 】
hasprerequisite 【 CONCEPTNET : smoke 】
hasprerequisite 【 CONCEPTNET : light_cigarette 】
haslastsubevent 【 CONCEPTNET : eat 】

-> 【 CONCEPTNET : quit 】
hasprerequisite 【 CONCEPTNET : smoke 】
hassubevent 【 CONCEPTNET : light_cigarette 】
haslastsubevent 【 CONCEPTNET : eat 】

-> 【 CONCEPTNET : quit 】
hasprerequisite 【 CONCEPTNET : smoke 】
hassubevent 【 CONCEPTNET : wait_for 】
hassubevent 【 CONCEPTNET : eat 】

-> 【 CONCEPTNET : quit 】
motivatedbygoal 【 CONCEPTNET : cash_in 】
hasprerequisite 【 CONCEPTNET : work 】
hasprerequisite 【 CONCEPTNET : eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : quit his job 】
xNeed 【 ATOMIC_EVENT : PersonX moves to texas 】
xEffect 【 ATOMIC_INFER : eats lots of bbq 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : to quit the party 】
xIntent 【 ATOMIC_EVENT : PersonX leaves immediately 】
xWant 【 ATOMIC_INFER : get something to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : to quit 】
xIntent 【 ATOMIC_EVENT : PersonX ends the day 】
xWant 【 ATOMIC_INFER : to get something to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : to quit 】
xWant 【 ATOMIC_EVENT : PersonX gets ___ anyway 】
xIntent 【 ATOMIC_INFER : to eat chocolate 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : to quit 】
xNeed 【 ATOMIC_EVENT : PersonX paves the way 】
xWant 【 ATOMIC_INFER : to eat something 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : people quit their rebellion 】
oEffect 【 ATOMIC_EVENT : PersonX prevents ___ from developing 】
xWant 【 ATOMIC_INFER : to eat healthy 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : want to quit smoking 】
xNeed 【 ATOMIC_EVENT : PersonX quits cold turkey 】
xWant 【 ATOMIC_INFER : to eat all the time 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : to quit their job 】
xNeed 【 ATOMIC_EVENT : PersonX feels happier 】
xNeed 【 ATOMIC_INFER : to eat some ice cream 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : to quit their job 】
xNeed 【 ATOMIC_EVENT : PersonX has stopped working 】
xIntent 【 ATOMIC_INFER : take a break from work perhaps to eat some food or rest themselves 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : to quit feeling hungry 】
xIntent 【 ATOMIC_EVENT : PersonX eats food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : has to quit soon after 】
xEffect 【 ATOMIC_EVENT : PersonX plays football again 】
xWant 【 ATOMIC_INFER : have something to eat 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : to quit his job 】
xNeed 【 ATOMIC_EVENT : PersonX moves to canada 】
xIntent 【 ATOMIC_INFER : to eat as much maple syrup as he can 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : quit smoking 】
xNeed 【 ATOMIC_EVENT : PersonX stays healthy 】
xNeed 【 ATOMIC_INFER : eat well 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : quit addictions 】
xWant 【 ATOMIC_EVENT : PersonX affects PersonX's health 】
xNeed 【 ATOMIC_INFER : eat only fast food 】

-> 【 CONCEPTNET : quit 】
-> 【 ATOMIC_INFER : quit addictions 】
xWant 【 ATOMIC_EVENT : PersonX affects PersonX's health 】
xWant 【 ATOMIC_INFER : eat healthy 】

### Path Statistics

In [115]:
import pandas as pd

In [116]:
df_query_count_for_each_qa = pd.DataFrame(query_count_for_each_qa) 
df_path_count_for_each_qa = pd.DataFrame(path_count_for_each_qa) 
df_path_count_for_each_query = pd.DataFrame(path_count_for_each_query)

In [117]:
df_query_count_for_each_qa.describe()

                 0
count  2994.000000
mean     37.943888
std      20.754742
min       3.000000
25%      24.000000
50%      34.000000
75%      47.000000
max     243.000000

In [119]:
df_path_count_for_each_query.describe()

                   0
count  113604.000000
mean      448.838087
std       448.906925
min         1.000000
25%        23.000000
50%       225.000000
75%      1002.000000
max      1520.000000

In [118]:
df_path_count_for_each_qa.describe()

                   0
count    2994.000000
mean    17030.661991
std     12946.222832
min        15.000000
25%      7665.500000
50%     14435.500000
75%     23024.000000
max    136368.000000

In [1]:
from transformers import BertModel, BertTokenizer, RobertaTokenizer, RobertaModel
tokenizer = RobertaTokenizer.from_pretrained('roberta-large')
model = RobertaModel.from_pretrained('roberta-large', output_hidden_states=True)

In [6]:
import transformers
import torch

In [7]:
transformers.__version__

'3.0.2'

In [8]:

def convert_qa_concept_to_bert_input(tokenizer, question, answer, concept, max_seq_length):
    qa_tokens = tokenizer.tokenize('Q: ' + question + ' A: ' + answer)
    concept_tokens = tokenizer.tokenize(concept)
    qa_tokens = qa_tokens[:max_seq_length - len(concept_tokens) - 3]
    tokens = [tokenizer.cls_token] + qa_tokens + [tokenizer.sep_token] + concept_tokens + [tokenizer.sep_token]
    input_ids = tokenizer.convert_tokens_to_ids(tokens)
    segment_ids = [0] * (len(qa_tokens) + 2) + [1] * (len(concept_tokens) + 1)

    assert len(input_ids) == len(segment_ids) == len(input_ids)

    # padding
    padding_id =  1 #args.model=='roberta'
    pad_len = max_seq_length - len(input_ids)
    input_mask = [1] * len(input_ids) + [0] * pad_len
    input_ids += [padding_id] * pad_len
    segment_ids += [0] * pad_len
    span = (len(qa_tokens) + 2, len(qa_tokens) + 2 + len(concept_tokens))

    assert span[1] + 1 == len(tokens)
    assert max_seq_length == len(input_ids) == len(segment_ids) == len(input_mask)

    return input_ids, input_mask, segment_ids, span

In [9]:
question = 'Carson was being noisy during the play rehearsal. Kai told Carson he must be quiet during the rehearsal or he couldnt stay.'
answer = 'god fly'
concept = 'fair fair'
max_seq_length = 64
input_ids, input_mask, segment_ids, span = convert_qa_concept_to_bert_input(tokenizer, question, answer, concept, max_seq_length)

In [16]:
print(input_mask)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [14]:
batch = [[input_ids,input_ids], [input_mask,input_mask]]#, [segment_ids,segment_ids]

batch = [torch.tensor(x, dtype=torch.long) for x in batch]
#batch = [x.to(device) for x in batch]
#inputs = {"input_ids": batch[0], "attention_mask": batch[1]}

outputs = model(*batch)
hidden_states = outputs[-1][-1]

In [13]:
hidden_states

tensor([[[-2.5704e-01, -6.2144e-02, -2.2433e-02,  ...,  1.0117e-01,
          -1.4716e-01,  2.4257e-01],
         [ 1.7927e-01, -1.9771e-01, -5.9680e-01,  ..., -1.7400e-01,
          -1.4143e+00,  4.7335e-01],
         [ 7.9476e-02, -1.9205e-03, -4.3239e-01,  ...,  4.4143e-02,
          -3.7674e-01, -1.2345e-01],
         ...,
         [-3.8002e-02,  1.2415e-02, -2.7992e-01,  ...,  7.0268e-04,
           9.3568e-02,  1.5369e-01],
         [-3.8002e-02,  1.2415e-02, -2.7992e-01,  ...,  7.0268e-04,
           9.3568e-02,  1.5369e-01],
         [-3.8002e-02,  1.2415e-02, -2.7992e-01,  ...,  7.0268e-04,
           9.3568e-02,  1.5369e-01]],

        [[-2.5704e-01, -6.2144e-02, -2.2433e-02,  ...,  1.0117e-01,
          -1.4716e-01,  2.4257e-01],
         [ 1.7927e-01, -1.9771e-01, -5.9681e-01,  ..., -1.7400e-01,
          -1.4143e+00,  4.7335e-01],
         [ 7.9476e-02, -1.9222e-03, -4.3239e-01,  ...,  4.4144e-02,
          -3.7674e-01, -1.2345e-01],
         ...,
         [-3.8002e-02,  1.2415e-02, -2.7992e-01,  ...,  7.0102e-04,
           9.3568e-02,  1.5369e-01],
         [-3.8002e-02,  1.2415e-02, -2.7992e-01,  ...,  7.0102e-04,
           9.3568e-02,  1.5369e-01],
         [-3.8002e-02,  1.2415e-02, -2.7992e-01,  ...,  7.0102e-04,
           9.3568e-02,  1.5369e-01]]], grad_fn=<NativeLayerNormBackward>)

In [8]:
tokenizer("Hello world")['input_ids']

TypeError: 'RobertaTokenizer' object is not callable

'<pad>'

In [36]:
mask_str = "any ___ "
#encoded_input = tokenizer.tokenize(mask_str)
tokenizer.convert_tokens_to_ids(tokenizer.sep_token)

2

In [16]:
text = "Replace me by any text you'd like."
encoded_input = tokenizer.tokenize(text)
input_ids = tokenizer.convert_tokens_to_ids(encoded_input)
segment_ids = [0] * (len(qa_tokens) + 2) + [1] * (len(concept_tokens) + 1)

In [34]:
text = "Replace me by ___ text you'd like."
tokenizer.encode_plus(text, text, padding="max_length", max_length=64)

{'input_ids': [0, 9064, 6406, 162, 30, 2165, 2788, 47, 1017, 101, 4, 2, 2, 9064, 6406, 162, 30, 2165, 2788, 47, 1017, 101, 4, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [ ]:
[0, 9064, 6406, 162, 30, 143, 2788, 47, 1017, 101, 4, 2,

In [56]:
from transformers import pipeline

In [68]:
nlp = pipeline('feature-extraction', model=model, tokenizer=tokenizer)
result = nlp(
     ['question What is the name of the repository ?',
     'context Pipeline have been included in the huggingface/transformers repository']
)

In [72]:
len(result[1])

15

In [63]:
bert_tokenizer = BertTokenizer.from_pretrained('bert-large-uncased', do_lower_case=True)
bert_model = BertModel.from_pretrained('bert-large-uncased', output_hidden_states=True)

In [37]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [38]:
device

device(type='cpu')

FileNotFoundError: [Errno 2] No such file or directory: 'data/connected_kb/socialiqa/features/train.roberta.inputs.3hop.pk'

(46700, 46700)